// Banque Anatomie convertie pour le moteur sandbox.js
// Format source: { c, l, q, o, a, e }

var MAIN_Q = [
  // CHAPITRE 1
  {c:"1",l:"Chap. 1",q:"Combien a-t-on de vraies côtes ?",o:["5","7","10","12"],a:1,e:"Vraies côtes = 7 paires (côtes 1–7) — s'articulent directement avec le sternum."},
  {c:"1",l:"Chap. 1",q:"De quel type sont les articulations zygapophysaires au niveau lombaire ?",o:["Trochléenne","Énarthrose","Arthrodies","Trochoïde"],a:2,e:"Les articulations zygapophysaires = ARTHRODIES (planes) à tous les niveaux vertébraux."},
  {c:"1",l:"Chap. 1",q:"De quel type sont les articulations costochondrales ?",o:["Synchondrose","Arthrodie","Symphyse","Condylienne"],a:0,e:"Les articulations costochondrales = SYNCHONDROSE (cartilage non ossifié entre côte et cartilage costal)."},
  {c:"1",l:"Chap. 1",q:"Pendant le mouvement de nutation, sélectionnez la réponse correcte :",o:["La pointe du sacrum va en avant","La base du sacrum va en arrière","Les os iliaques tournent en avant puis vers le sol","L'ischium tourne en avant et vers le ciel"],a:0,e:"Nutation : la pointe du sacrum VA EN AVANT. La base du sacrum va en arrière. L'ischium va en arrière et vers le bas."},
  {c:"1",l:"Chap. 1",q:"L'épine sciatique est :",o:["Inférieure à la petite échancrure sciatique","Supérieure à l'épine postérieure inférieure iliaque","Entre les deux échancrures sciatiques","Supérieure à la grande échancrure sciatique"],a:2,e:"L'épine sciatique est ENTRE la grande et la petite échancrure sciatique."},
  {c:"1",l:"Chap. 1",q:"Quelles sont les deux types d'articulations entre C1 et C2 ?",o:["Trochoïde et arthrodie","Arthrodie et trochléenne","Trochléenne et condylienne","Trochoïde et condylienne"],a:0,e:"C1–C2 : atlanto-axoïdienne médiane = TROCHOÏDE (rotation) + atlanto-axoïdiennes latérales = ARTHRODIES."},
  {c:"1",l:"Chap. 1",q:"Où peut-on trouver des processus mamillaires ?",o:["Proche des zygapophysaires des vertèbres lombaires","Sur les processus transverses des vertèbres lombaires","Sur les processus transverses des vertèbres thoraciques","Proche des zygapophysaires des vertèbres thoraciques"],a:0,e:"Les processus mamillaires se trouvent proche des zygapophysaires des VERTÈBRES LOMBAIRES."},
  {c:"1",l:"Chap. 1",q:"Combien y a-t-il de vertèbres thoraciques ?",o:["10","7","12","5"],a:2,e:"12 vertèbres thoraciques (T1–T12). 7 cervicales, 5 lombaires, 5 sacrées (fusionnées), 4 coccygiennes."},
  {c:"1",l:"Chap. 1",q:"Le sacrum résulte de la fusion de combien de vertèbres ?",o:["3","4","5","6"],a:2,e:"Le sacrum = fusion de 5 vertèbres sacrées (S1–S5)."},
  {c:"1",l:"Chap. 1",q:"Quelle courbure vertébrale est une lordose ?",o:["Courbure thoracique","Courbure sacrée","Courbure lombaire","Courbure cervicale et lombaire"],a:3,e:"Les LORDOSES (concavité postérieure) sont cervicale et lombaire. Les CYPHOSES (concavité antérieure) sont thoracique et sacrée."},
  {c:"1",l:"Chap. 1",q:"Les côtes flottantes sont les côtes :",o:["1 à 7","8 à 10","11 et 12","1 à 5"],a:2,e:"Côtes FLOTTANTES = 11 et 12 (n'ont aucune connexion avec le sternum ni avec une autre côte par du cartilage)."},
  {c:"1",l:"Chap. 1",q:"L'atlas (C1) se distingue des autres vertèbres car il :",o:["A un processus épineux très long","N'a pas de corps vertébral","Présente des processus mamillaires","A deux facettes articulaires inférieures convexes"],a:1,e:"L'atlas (C1) n'a PAS de corps vertébral. Il est remplacé par un arc antérieur qui s'articule avec la dent de l'axis."},

  // CHAPITRE 2
  {c:"2",l:"Chap. 2",q:"La suture lambdoïde est établie entre les os :",o:["Frontal et pariétal","Pariétal et occipital","Les deux pariétaux","Temporal et pariétal"],a:1,e:"Suture lambdoïde = PARIÉTAUX + OCCIPITAL. Coronale = frontal + pariétaux. Sagittale = entre les deux pariétaux."},
  {c:"2",l:"Chap. 2",q:"Laquelle des affirmations concernant le splanchnocrâne est VRAIE ?",o:["Il est constitué de 8 os","2 impaires et 4 paires","Les os paires sont : maxillaires, palatins, zygomatiques, nasaux, unguis, cornets inf.","Les os impaires sont le vomer, le palatin et l'ethmoïde"],a:2,e:"Splanchnocrâne : os PAIRES = maxillaires + palatins + zygomatiques + nasaux + unguis + cornets inf. Os impaires = mandibule + vomer."},
  {c:"2",l:"Chap. 2",q:"Dans quelle vue se trouve l'astérion ?",o:["Antérieure","Postérieure","Latérale","Supérieure"],a:2,e:"L'astérion est un point craniométrique situé en vue LATÉRALE, à la jonction des os temporal, occipital et pariétal."},
  {c:"2",l:"Chap. 2",q:"La mandibule s'articule avec lequel des os suivants ?",o:["Sphénoïde","Zygomatique","Temporal","Maxillaire"],a:2,e:"La mandibule s'articule avec le TEMPORAL = ATM (articulation temporo-mandibulaire)."},
  {c:"2",l:"Chap. 2",q:"Par quel foramen passe le système nerveux central ?",o:["Le foramen magnum","Le foramen ovale","Le foramen épineux","Le canal hypoglosse"],a:0,e:"Le système nerveux central (bulbe rachidien / moelle épinière) passe par le FORAMEN MAGNUM."},
  {c:"2",l:"Chap. 2",q:"Le neurocrane est composé de combien d'os chez l'adulte ?",o:["6","7","8","9"],a:2,e:"Neurocrane = 8 os : frontal + occipital + sphénoïde + ethmoïde + 2 pariétaux + 2 temporaux."},
  {c:"2",l:"Chap. 2",q:"La fosse crânienne postérieure contient :",o:["Le cerveau et le cervelet","Le cervelet et le tronc cérébral","Les lobes frontaux","Les lobes temporaux"],a:1,e:"Fosse crânienne POSTÉRIEURE = cervelet + tronc cérébral. Antérieure = lobes frontaux. Moyenne = lobes temporaux."},

  // CHAPITRE 3
  {c:"3",l:"Chap. 3",q:"Lequel de ces muscles ne présente pas d'insertion sur la scapula ?",o:["Petit rhomboïde","Scalène postérieur","Trapèze","Omohyoïdien"],a:1,e:"Scalène postérieur → 2e côte. L'omohyoïdien ORIGINE sur la scapula."},
  {c:"3",l:"Chap. 3",q:"Lequel ne fait PAS partie des muscles érecteurs de la colonne ?",o:["L'inter-épineux","L'épineux","L'iliocostal","Le longissimus"],a:0,e:"Érecteurs = Ilio-costal + Longissimus + Épineux. L'inter-épineux = muscle intersegmentaire."},
  {c:"3",l:"Chap. 3",q:"Quelle est l'origine/insertion de l'oblique inférieur des sous-occipitaux ?",o:["Tubercule post. atlas → ligne nucale inf.","Apoph. épineuse axis → processus transverse atlas","Processus transverse atlas → entre lignes nuchales","Apoph. épineuse axis → ligne nucale inf."],a:1,e:"Oblique INF. : épi. AXIS (C2) → apoph. transverse ATLAS (C1). Seul sous-occipital sans insertion sur l'occipital."},
  {c:"3",l:"Chap. 3",q:"Lequel n'est PAS innervé par les rameaux postérieurs des nerfs spinaux ?",o:["Inter-transversaire","Longissimus","Trapèze","Ilio-costal"],a:2,e:"TRAPÈZE = nerf ACCESSOIRE XI + C3–C4. Inter-transversaires = rameaux ventraux."},
  {c:"3",l:"Chap. 3",q:"Quels muscles vont d'une apophyse transverse à l'épineuse de 3 ou 4 vertèbres au-dessus ?",o:["Le multifide","Le rotateur long","Le rotateur court","Le semi-épineux"],a:0,e:"MULTIFIDES : apoph. transverse → apoph. épineuse 3–4 vertèbres au-dessus."},
  {c:"3",l:"Chap. 3",q:"L'innervation motrice du trapèze est assurée par :",o:["Nerf thoracodorsal C6–C8","Nerf accessoire XI + proprioception C3–C4","Nerf dorsal scapula C4–C5","Plexus cervical C2–C4"],a:1,e:"Trapèze = nerf ACCESSOIRE XI (motricité) + C3–C4 (proprioception)."},
  {c:"3",l:"Chap. 3",q:"L'ordre des érecteurs de latéral à médial est :",o:["Épineux → Longissimus → Ilio-costale","Ilio-costale → Épineux → Longissimus","Longissimus → Ilio-costale → Épineux","Ilio-costale → Longissimus → Épineux"],a:3,e:"De latéral à médial : ILE (Ilio-costale → Longissimus → Épineux)."},
  {c:"3",l:"Chap. 3",q:"Les 4 origines du grand dorsal sont :",o:["Épi. T5–L5, coccyx, crête iliaque, côtes VIII–X","Épi. T7–L5, sacrum, crête iliaque, côtes X–XII","Épi. T7–L3, sacrum, épine iliaque, côtes IX–XII","Épi. T6–L4, sacrum, crête iliaque, côtes IX–XI"],a:1,e:"Grand dorsal : épi. T7–L5 + sacrum + crête iliaque + côtes X–XII."},
  {c:"3",l:"Chap. 3",q:"Le petit droit postérieur de la tête prend origine sur :",o:["Apoph. épineuse axis C2","Apoph. transverse atlas C1","Tubercule postérieur atlas C1","Apoph. épineuse C3"],a:2,e:"Petit droit post. : tubercule post. ATLAS (C1) → occipital partie méd. Action : extension tête uniquement."},
  {c:"3",l:"Chap. 3",q:"Les multifides sautent combien de vertèbres ?",o:["1 à 2","3 à 4","Plus de 4 (6–8)","5 à 6"],a:1,e:"Multifides = 3–4 vertèbres. Rotateurs courts = 1. Rotateurs longs = 2. Semi-épineux = plus de 4."},
  {c:"3",l:"Chap. 3",q:"Quelle est l'action du splénius en contraction BILATÉRALE ?",o:["Rotation homolatérale","Inclinaison latérale","Extension du cou","Flexion du cou"],a:2,e:"Bilatéral = EXTENSION du cou. Unilatéral = rotation homolatérale + inclinaison."},
  {c:"3",l:"Chap. 3",q:"Les intertransversaires sont innervés par :",o:["Branches dorsales","Branches ventrales","Nerf accessoire XI","Nerf dorsal scapula"],a:1,e:"Exception : intertransversaires = branches VENTRALES. Tous les autres intrinsèques du dos = branches dorsales."},

  // CHAPITRE 4
  {c:"4",l:"Chap. 4",q:"Quel muscle NE S'ORIGINE PAS à la partie basilaire de l'occipital ?",o:["Long de la tête","Splénius de la tête","Long du cou","Droit antérieur de la tête"],a:1,e:"Le splénius de la TÊTE S'INSÈRE sur l'occipital (ne prend pas origine là)."},
  {c:"4",l:"Chap. 4",q:"Le SCM n'intervient PAS dans :",o:["L'inclinaison de la tête","L'extension de la tête","La rotation de la tête","L'inspiration accessoire"],a:1,e:"Le SCM ne fait PAS l'extension de la tête. Il fait : flexion (bilat.) + rotation contro. + inclinaison homo. + inspiration accessoire."},
  {c:"4",l:"Chap. 4",q:"Lequel est le plus superficiel ?",o:["Thyro-hyoïdien","Sterno-thyroïdien","Long du cou","Sterno-hyoïdien"],a:3,e:"Le STERNO-HYOÏDIEN est le muscle infra-hyoïdien le plus SUPERFICIEL."},
  {c:"4",l:"Chap. 4",q:"Affirmation FAUSSE sur les nerfs des muscles supra-hyoïdiens :",o:["Génio-hyoïdien → hypoglosse","Mylo-hyoïdien → nerf mylohyoïdien","Ventre ant. digastrique → nerf facial","Stylo-hyoïdien → nerf facial"],a:2,e:"FAUX : ventre ANT. digastrique = nerf MYLOHYOÏDIEN (V). Ventre POST. = facial (VII)."},
  {c:"4",l:"Chap. 4",q:"Lequel N'EST PAS un muscle infra-hyoïdien ?",o:["Stylo-hyoïdien","Sterno-thyroïde","Sterno-hyoïde","Omo-hyoïde"],a:0,e:"STYLO-HYOÏDIEN = muscle SUPRA-hyoïdien (innervé par facial VII)."},
  {c:"4",l:"Chap. 4",q:"Le thyrohyoïdien est innervé par :",o:["Anse cervicale C1–C3 uniquement","Nerf accessoire XI","Anse cervicale + hypoglosse XII","Nerf facial VII"],a:2,e:"Thyrohyoïdien = anse cervicale + hypoglosse XII. Seul infra-hyoïdien innervé par le XII."},
  {c:"4",l:"Chap. 4",q:"Le scalène postérieur s'insère sur :",o:["1ère côte","2e côte","3e côte","Apoph. transverse C7"],a:1,e:"Scalène post. : C4–C6 → 2e côte. Scalènes ant. et moyen → 1ère côte."},
  {c:"4",l:"Chap. 4",q:"Qu'est-ce qui passe dans le triangle interscalénique ?",o:["Artère carotide + nerf vague","Plexus brachial + artère sous-clavière","Veine jugulaire + nerf phrénique","Nerf phrénique + artère sous-clavière"],a:1,e:"Triangle interscalénique (entre scalène ant. et moyen) : PLEXUS BRACHIAL + ARTÈRE SOUS-CLAVIÈRE."},
  {c:"4",l:"Chap. 4",q:"Le SCM en contraction unilatérale :",o:["Flexion + rotation homolatérale","Extension + rotation controlatérale","Rotation controlatérale + inclinaison homolatérale","Flexion + inclinaison controlatérale"],a:2,e:"SCM unilatéral : rotation CONTRO. + inclinaison HOMO. Bilatéral : flexion tête."},
  {c:"4",l:"Chap. 4",q:"Le long du cou en contraction unilatérale produit :",o:["Rotation homolatérale","Rotation controlatérale + inclinaison","Extension cervicale","Flexion + rotation homolatérale"],a:1,e:"Long du cou unilatéral = inclinaison + rotation CONTROLATÉRALE. Bilatéral = flexion cervicale."},

  // CHAPITRE 5
  {c:"5",l:"Chap. 5",q:"Quel muscle de l'ATM s'insère sur le disque ?",o:["Masséter","Temporal","Ptérygoïdien latéral","Ptérygoïdien médial"],a:2,e:"Ptérygoïdien LATÉRAL = seul masticateur qui s'insère sur le disque + col mandibule + capsule."},
  {c:"5",l:"Chap. 5",q:"Les muscles masticateurs sont innervés par :",o:["Le nerf facial","Le nerf mandibulaire (V3)","Le nerf vague","Le nerf accessoire"],a:1,e:"Tous les masticateurs = NC V branche MANDIBULAIRE (V3)."},
  {c:"5",l:"Chap. 5",q:"Lors de l'ouverture de la bouche, le ménisque :",o:["Recule","Reste au même endroit","Se déplace latéralement","Avance"],a:3,e:"À l'ouverture : le ménisque AVANCE sur le tubercule articulaire."},
  {c:"5",l:"Chap. 5",q:"Lequel n'a PAS pour fonction d'abaisser la mâchoire ?",o:["Stylo-hyoïdien","Digastrique","Géniohyoïdien","Mylohyoïdien"],a:0,e:"STYLO-HYOÏDIEN élève et repositionne l'hyoïde."},
  {c:"5",l:"Chap. 5",q:"Lequel a pour action 'souffler' ?",o:["Orbiculaire de la bouche","Risorius","Abaisseur de l'angle de la bouche","Buccinateur"],a:3,e:"Le BUCCINATEUR est le muscle qui permet de souffler. Il est recouvert par le masséter."},
  {c:"5",l:"Chap. 5",q:"Les fibres postérieures du temporal réalisent :",o:["L'élévation de la mandibule","La protrusion","La rétraction de la mandibule","La diduction"],a:2,e:"Fibres POST. temporal = RÉTRACTION mandibule. Fibres ant. + moy. = élévation."},
  {c:"5",l:"Chap. 5",q:"Le masséter s'insère sur :",o:["Apophyse coronoïde","Face latérale branche mandibule","Col mandibule","Fosse ptérygoïdienne"],a:1,e:"Masséter : arcade zygomatique → face LATÉRALE branche mandibule."},
  {c:"5",l:"Chap. 5",q:"Le ligament temporo-mandibulaire latéral protège :",o:["La fosse ptérygoïdienne","Le méat acoustique externe + limite mvt arrière","L'articulation des mvt vers l'avant","Le nerf auriculotemporal"],a:1,e:"Lig. temporo-mand. lat. : arcade zygomatique → col mandibule. Limite mvt ARRIÈRE + protège méat acoustique externe."},
  {c:"5",l:"Chap. 5",q:"La classification fonctionnelle de l'ATM est :",o:["Énarthrose + condylienne","Ginglymo-arthrodiale (charnière + glissement)","Arthrodie + trochoïde","Trochoïde + condylienne"],a:1,e:"ATM = ginglymo-arthrodiale. Ginglyme = charnière. Arthrodiale = glissement."},

  // THÈME 6
  {c:"6",l:"Thème 6",q:"Lequel de ces muscles est inspirateur ?",o:["Dentelé postérieur supérieur","Dentelé postérieur inférieur","Transverse du thorax","Ils sont tous inspirateurs"],a:0,e:"Dentelé post. SUP. = INSPIRATEUR (élève côtes II–V). Post. INF. = expirateur."},
  {c:"6",l:"Thème 6",q:"Sur laquelle le diaphragme NE s'insère PAS ?",o:["Apophyse transverse de T12","Apophyse xiphoïde","Corps vertébraux L1–L3","Côtes 7 à 12"],a:0,e:"Diaphragme ne s'insère PAS sur l'apophyse TRANSVERSE de T12."},
  {c:"6",l:"Thème 6",q:"L'origine lombaire du diaphragme :",o:["Permet le passage du psoas sous le lig. arqué latéral","Permet le passage du psoas sous le lig. arqué médial","Présente deux piliers sur les vertèbres thoraciques","Permet le passage de la veine cave"],a:1,e:"Lig. arqué MÉDIAL = passage du PSOAS. Lig. arqué LATÉRAL = passage du carré des lombes."},
  {c:"6",l:"Thème 6",q:"Réponse FAUSSE par rapport au diaphragme :",o:["Innervé par le nerf phrénique","Sépare la cavité abdominale du pelvis","La contraction augmente le volume interne","Présente un foramen pour veine cave, aorte et œsophage"],a:1,e:"FAUX : le diaphragme sépare la cavité THORACIQUE de la cavité ABDOMINALE."},
  {c:"6",l:"Thème 6",q:"Par rapport au diaphragme, indiquez la bonne réponse :",o:["Il est situé entre cavité thoracique et abdominale","Son insertion est le centre phrénique","Il est inspirateur","Tout ce qui précède est correct"],a:3,e:"TOUT EST CORRECT : localisation thoraco-abdominale + centre phrénique = tendon central + inspirateur."},
  {c:"6",l:"Thème 6",q:"À quel niveau passe l'aorte dans le diaphragme ?",o:["T8","T10","T12","T6"],a:2,e:"T12 = aorte + canal thoracique + veine azygos. T8 = veine cave. T10 = œsophage."},
  {c:"6",l:"Thème 6",q:"Le faisceau neurovasculaire intercostal passe entre :",o:["Externes et internes","Internes et intimes","Intimes et plèvre","Externes et plèvre"],a:1,e:"Faisceau neurovasculaire = entre intercostaux INTERNES et INTIMES."},
  {c:"6",l:"Thème 6",q:"Le ligament arqué LATÉRAL du diaphragme est en rapport avec :",o:["Le psoas","L'aorte","Le carré des lombes","La veine cave inférieure"],a:2,e:"Lig. arqué LATÉRAL = carré des lombes. Lig. arqué MÉDIAL = psoas."},
  {c:"6",l:"Thème 6",q:"Le pilier DROIT du diaphragme s'insère sur :",o:["L1–L2","L1–L4","L1–L3","L2–L4"],a:2,e:"Pilier DROIT : L1–L3. Pilier GAUCHE : L1–L2. Le droit est plus long (entoure l'œsophage)."},
  {c:"6",l:"Thème 6",q:"Les intercostaux internes s'étendent :",o:["Du tubercule costal aux cartilages costaux","De la tête costale à l'angle costal","De l'angle costal à 5–6 cm du sternum","De l'angle costal au sternum"],a:3,e:"Intercostaux INTERNES : angle costal → sternum. EXTERNES : tubercule costal → cartilages costaux."},
  {c:"6",l:"Thème 6",q:"L'innervation du diaphragme est assurée par :",o:["Nerfs intercostaux T6–T12","Anse cervicale C1–C3","Nerf phrénique C3–C5","Branches post. C4–C6"],a:2,e:"Diaphragme = nerf PHRÉNIQUE C3–C5."},

  // CHAPITRE 7
  {c:"7",l:"Chap. 7",q:"Concernant le droit de l'abdomen au-dessus des EIAS :",o:["Il est postérieur à l'aponévrose de l'oblique interne","Il est antérieur à l'aponévrose de l'oblique externe","Il est postérieur à l'aponévrose du transverse","Il est entouré par l'aponévrose de l'oblique interne"],a:3,e:"Au-dessus EIAS : le grand droit est ENTOURÉ (feuillet ant. = oblique ext. + ½ oblique int. / post. = ½ oblique int. + transverse)."},
  {c:"7",l:"Chap. 7",q:"Par les fibres de quel muscle est formé le CRÉMASTER ?",o:["Oblique externe","Oblique interne","Transverse","Droit de l'abdomen"],a:1,e:"Crémaster = fibres de l'OBLIQUE INTERNE qui descendent vers le testicule."},
  {c:"7",l:"Chap. 7",q:"Pour une flexion + rotation de tronc vers la gauche :",o:["Oblique ext. homo. + oblique int. contro.","Seulement l'oblique interne","Oblique ext. contro. + oblique int. homo.","Toutes les réponses sont fausses"],a:2,e:"Rotation gauche = oblique ext. DROIT (contro.) + oblique int. GAUCHE (homo.). E-C / I-H."},
  {c:"7",l:"Chap. 7",q:"Avec quel muscle l'oblique externe s'interdigite ?",o:["Grand dorsal + grand pectoral","Grand dorsal + dentelé antérieur","Dentelé antérieur + grand pectoral","Ce n'est pas l'externe mais l'interne"],a:1,e:"Oblique externe s'interdigite avec GRAND DORSAL + DENTELÉ ANTÉRIEUR."},
  {c:"7",l:"Chap. 7",q:"La ligne arquée de Douglas est :",o:["La jonction des aponévroses sur la ligne médiane","La limite supérieure de la gaine du droit","La limite inférieure de la paroi postérieure de la gaine","Le bord inférieur du lig. inguinal"],a:2,e:"Ligne arquée = limite INFÉRIEURE de la paroi POSTÉRIEURE de la gaine du droit."},
  {c:"7",l:"Chap. 7",q:"Le ligament inguinal est formé par :",o:["Bord supérieur aponévrose oblique interne","Bord inférieur épaissi aponévrose oblique externe","Bord inférieur aponévrose du transverse","Bord supérieur aponévrose oblique externe"],a:1,e:"Lig. inguinal = bord inf. épaissi aponévrose OBLIQUE EXTERNE. De l'EIAS au tubercule pubien."},
  {c:"7",l:"Chap. 7",q:"Le canal inguinal contient chez la femme :",o:["Le cordon spermatique","Le nerf ilio-inguinal","L'artère épigastrique inférieure","Le ligament rond de l'utérus"],a:3,e:"Canal inguinal ♀ = LIGAMENT ROND de l'utérus. ♂ = cordon spermatique."},
  {c:"7",l:"Chap. 7",q:"L'oblique interne en contraction unilatérale réalise :",o:["Rotation controlatérale","Extension du tronc","Rotation homolatérale","Compression des viscères"],a:2,e:"Oblique interne unilatéral = rotation HOMOLATÉRALE. Mnémotechnique : I-H."},
  {c:"7",l:"Chap. 7",q:"Quelle est la fonction principale du transverse de l'abdomen ?",o:["Flexion du tronc","Rotation controlatérale","Compression et soutien des viscères","Inclinaison latérale"],a:2,e:"Transverse = COMPRESSION + soutien viscères + maintien pression intra-abdominale."},
  {c:"7",l:"Chap. 7",q:"La ligne blanche s'étend de :",o:["La 7e côte au pubis","L'EIAS au pubis","L'apophyse xiphoïde au pubis","La crête iliaque au pubis"],a:2,e:"Ligne blanche : xiphoïde → pubis. Jonction des 3 aponévroses controlatérales."},

  // CHAPITRE 8
  {c:"8",l:"Chap. 8",q:"Lequel se trouve dans le plan moyen (diaphragme urogénital) ?",o:["Bulbo-spongieux","Sphincter externe de l'anus","Transverse profond du périnée","Pubo-rectal"],a:2,e:"Plan MOYEN = transverse PROFOND du périnée + sphincter urétral."},
  {c:"8",l:"Chap. 8",q:"Lequel NE s'insère PAS sur le centre tendineux du périnée ?",o:["Sphincter de l'anus","Bulbo-spongieux","Transverse superficiel du périnée","Ischio-caverneux"],a:3,e:"L'ISCHIO-CAVERNEUX s'insère sur la base du pénis/clitoris, pas sur le corps périnéal."},
  {c:"8",l:"Chap. 8",q:"Lequel est un faisceau du muscle élévateur de l'anus ?",o:["Ano-coccygien","Sacro-coccygien","Pubo-coccygien","Coccygien"],a:2,e:"Élévateur de l'anus = puborectal + PUBOCOCCYGIEN + iliococcygien. Le coccygien est un muscle séparé."},
  {c:"8",l:"Chap. 8",q:"Lequel de ces muscles est le plus antérieur ?",o:["Transverse superficiel du périnée","Ischio-caverneux","Coccygien","Sphincter externe de l'anus"],a:1,e:"L'ISCHIO-CAVERNEUX est le plus antérieur (s'insère sur la base du pénis/clitoris)."},
  {c:"8",l:"Chap. 8",q:"Le nerf pudendal sort par quel foramen ?",o:["Petit foramen sciatique","Grand foramen sciatique","Foramen obturateur","Foramen sacré"],a:1,e:"Nerf pudendal SORT par le grand foramen sciatique et ENTRE par le petit foramen sciatique → canal d'Alcock."},
  {c:"8",l:"Chap. 8",q:"Les 3 faisceaux de l'élévateur de l'anus sont :",o:["Ilio-coccygien + ischio-coccygien + pubo-coccygien","Puborectal + pubococcygien + iliococcygien","Puborectal + ischiococcygien + pubococcygien","Puborectal + iliococcygien + coccygien"],a:1,e:"Élévateur de l'anus = puborectal + pubococcygien + iliococcygien."},
  {c:"8",l:"Chap. 8",q:"Le périnée a la forme d'un :",o:["Triangle","Carré","Losange","Hexagone"],a:2,e:"Périnée = LOSANGE. Limites : symphyse pubienne + lig. sacro-tubéreux + tubérosités ischiatiques + sacrum."},
  {c:"8",l:"Chap. 8",q:"Le sac de Douglas se trouve :",o:["Entre vessie et utérus","Entre utérus et rectum","Entre rectum et sacrum","Entre vessie et rectum"],a:1,e:"Sac de Douglas = sac recto-utérin entre l'utérus et le rectum chez la femme."},
  {c:"8",l:"Chap. 8",q:"Le ligament le plus important pour stabiliser l'utérus est :",o:["Ligament pubo-cervical","Ligament utéro-sacré","Ligament cardinal","Ligament large"],a:2,e:"Ligament CARDINAL = le plus important. Col utérus → paroi pelvienne latérale."},

  // CHAPITRE 9
  {c:"9",l:"Chap. 9",q:"La moelle épinière se termine normalement entre :",o:["T12 et L1","L1 et L2","L2 et L3","L3 et L4"],a:1,e:"Chez l'adulte, la moelle se termine entre L1 et L2. En dessous = queue de cheval."},
  {c:"9",l:"Chap. 9",q:"L'espace épidural contient :",o:["Le LCR","Tissu conjonctif + graisse + plexus veineux","La pie-mère","Le nerf phrénique"],a:1,e:"Espace épidural = entre dure-mère et os. Contient tissu conjonctif + graisse + plexus veineux."},
  {c:"9",l:"Chap. 9",q:"Combien y a-t-il de paires de nerfs rachidiens ?",o:["28","33","31","29"],a:2,e:"31 paires : 8C + 12T + 5L + 5S + 1Co."},
  {c:"9",l:"Chap. 9",q:"La méninge la plus interne est :",o:["La dure-mère","L'arachnoïde","La pie-mère","Le LCR"],a:2,e:"Pie-mère = la plus interne, collée à la moelle. Arachnoïde = intermédiaire. Dure-mère = la plus externe."},
  {c:"9",l:"Chap. 9",q:"La racine postérieure d'un nerf rachidien est :",o:["Motrice","Sensitive","Mixte","Végétative"],a:1,e:"Racine POSTÉRIEURE = sensitive. Racine ANTÉRIEURE = motrice."},
  {c:"9",l:"Chap. 9",q:"Le bord antérieur du foramen intervertébral est formé par :",o:["Les processus articulaires","Le disque intervertébral","Les pédicules","Le ligament jaune"],a:1,e:"Bord ANT. = disque intervertébral. Bord POST. = processus articulaires + articulation zygapophysaire."},
  {c:"9",l:"Chap. 9",q:"Le nerf phrénique est issu de :",o:["C1–C3","C2–C4","C3–C5","C4–C6"],a:2,e:"Nerf phrénique = C3–C5. Mnémotechnique : C3-C4-C5 keep the diaphragm alive !"},
  {c:"9",l:"Chap. 9",q:"La queue de cheval est formée par :",o:["La moelle épinière sous L1","Les racines L2–S5","Les nerfs sacrés uniquement","Le filum terminale"],a:1,e:"Queue de cheval = racines nerveuses L2–S5 qui descendent dans le canal rachidien."},
  {c:"9",l:"Chap. 9",q:"La rachianesthésie injecte dans :",o:["L'espace épidural","L'espace sous-arachnoïdien","Entre dure-mère et arachnoïde","Le canal central"],a:1,e:"Rachianesthésie = espace SOUS-ARACHNOÏDIEN. Péridurale = espace épidural."},

  // CHAPITRE 2.2
  {c:"22",l:"Chap. 2.2",q:"Quel est le type de l'articulation coxo-fémorale ?",o:["Condylienne","Plane","Énarthrose","Trochoïde"],a:2,e:"Coxo-fémorale = ÉNARTHROSE (sphérique), 3 degrés de liberté."},
  {c:"22",l:"Chap. 2.2",q:"Proposition VRAIE à propos du lig. ilio-fémoral ?",o:["Se tend en extension + stabilise en position bipède","Se tend en extension + stabilise en position quadrupède","Se tend en flexion + stabilise en position bipède","Se tend en flexion + stabilise en position quadrupède"],a:0,e:"Lig. ilio-fémoral : se tend en EXTENSION → maintien posture BIPÈDE."},
  {c:"22",l:"Chap. 2.2",q:"Lequel a la plus grande amplitude articulaire à la hanche ?",o:["Flexion","Extension","Rotation externe","Abduction"],a:0,e:"Flexion hanche = 120° = la plus grande amplitude."},
  {c:"22",l:"Chap. 2.2",q:"Affirmation FAUSSE à propos de la flexion de hanche ?",o:["Amplitude plus importante avec genou en flexion","Le psoas-iliaque participe","Le sartorius participe","Le lig. pubo-fémoral limite le mouvement"],a:3,e:"FAUX : lig. PUBO-FÉMORAL limite l'ABDUCTION + rotation lat., pas la flexion."},
  {c:"22",l:"Chap. 2.2",q:"Le lig. ischio-fémoral limite la rotation interne de hanche ?",o:["Vrai","Faux"],a:0,e:"VRAI. Le lig. ischio-fémoral limite la ROTATION MÉDIALE."},
  {c:"22",l:"Chap. 2.2",q:"Quelle action NE fait PAS le psoas-iliaque ?",o:["Flexion du tronc","Extension du tronc","Antéversion du pelvis","Hyperlordose lombaire"],a:1,e:"Psoas-iliaque ne fait PAS l'extension du tronc."},
  {c:"22",l:"Chap. 2.2",q:"Action du piriforme lorsque la hanche est fléchie ?",o:["Abduction","Adduction","Rotation interne","Rotation externe"],a:2,e:"Piriforme en FLEXION = rotation INTERNE + abduction."},
  {c:"22",l:"Chap. 2.2",q:"L'obturateur interne s'insère sur le petit trochanter ?",o:["Vrai","Faux"],a:1,e:"FAUX. Obturateur interne → face MÉD. GRAND trochanter. Petit trochanter = psoas-iliaque."},
  {c:"22",l:"Chap. 2.2",q:"Lequel ne s'insère PAS sur la tubérosité ischiatique ?",o:["Les jumeaux","L'obturateur externe","Carré fémoral","Semi-tendineux"],a:1,e:"Obturateur EXTERNE → fosse trochantérique. Les autres → tubérosité ischiatique."},
  {c:"22",l:"Chap. 2.2",q:"Moyen glutéal et grand glutéal ont la même innervation ?",o:["Vrai","Faux"],a:1,e:"FAUX. Moyen glutéal = nerf glutéal SUPÉRIEUR. Grand glutéal = nerf glutéal INFÉRIEUR."},
  {c:"22",l:"Chap. 2.2",q:"Le ligament pubo-fémoral limite :",o:["La flexion et la rotation médiale","L'extension et la rotation latérale","L'abduction et la rotation latérale","La flexion et l'adduction"],a:2,e:"Lig. pubo-fémoral : branche pubienne → fosse intertrochantérienne. Limite ABDUCTION + rotation LATÉRALE."},
  {c:"22",l:"Chap. 2.2",q:"Le psoas-iliaque s'insère sur :",o:["Le grand trochanter","Le petit trochanter","La ligne intertrochantérienne","La tubérosité glutéale"],a:1,e:"Psoas-iliaque : T12–L5 + fosse iliaque → PETIT trochanter."},

  // CHAPITRE 2.3
  {c:"23",l:"Chap. 2.3",q:"De quel type est l'articulation du genou ?",o:["Condylienne","Trochlée modifiée","Trochoïde","Symphyse"],a:1,e:"Genou = synoviale en TROCHLÉE MODIFIÉE. 2 degrés : flexion/extension + rotation axiale."},
  {c:"23",l:"Chap. 2.3",q:"Concernant les cavités glénoïdes du tibia :",o:["Les deux concaves dans tous les plans","Médiale concave transv. + convexe antéropost.","Latérale concave transv. + convexe antéropost.","Médiale concave antéropost. + convexe transv."],a:2,e:"Cavité glénoïde LATÉRALE = concave transv. + CONVEXE antéropost. Médiale = concave dans les DEUX plans."},
  {c:"23",l:"Chap. 2.3",q:"La capsule condylienne du genou :",o:["Adhère avec le ménisque médial","Adhère avec le ménisque latéral","N'adhère avec aucun","Adhère avec les deux"],a:1,e:"La capsule adhère avec le ménisque LATÉRAL. Le LCM adhère avec le ménisque médial."},
  {c:"23",l:"Chap. 2.3",q:"Les ligaments croisés du genou :",o:["LCP limite l'extension","LCA limite la flexion","LCP est sollicité en flexion","LCA se tend en flexion"],a:2,e:"LCP est SOLLICITÉ en FLEXION. LCA se TEND en EXTENSION."},
  {c:"23",l:"Chap. 2.3",q:"Les ligaments croisés sont :",o:["Extra-capsulaires et extra-synoviaux","Intra-capsulaires et intra-synoviaux","Extra-capsulaires et intra-synoviaux","Intra-capsulaires et extra-synoviaux"],a:3,e:"LCA + LCP = INTRA-capsulaires + EXTRA-synoviaux."},
  {c:"23",l:"Chap. 2.3",q:"Rotation externe du tibia = rotation interne du genou ?",o:["Vrai","Faux"],a:0,e:"VRAI. Rotations tibia/genou sont inverses."},
  {c:"23",l:"Chap. 2.3",q:"Tout le quadriceps est bi-articulaire ?",o:["Vrai","Faux"],a:1,e:"FAUX. Seul le DROIT FÉMORAL est biarticulaire. Les 3 vastes = monoarticulaires."},
  {c:"23",l:"Chap. 2.3",q:"Lequel ne fait PAS partie de la patte d'oie superficielle ?",o:["Semi-tendineux","Semi-membraneux","Gracile","Sartorius"],a:1,e:"SEMI-MEMBRANEUX = patte d'oie PROFONDE (3 tendons). Superficielle = Sartorius + Gracile + Semi-tendineux."},
  {c:"23",l:"Chap. 2.3",q:"L'amplitude de la flexion active du genou est de :",o:["120°","145°","135°","160°"],a:2,e:"Flexion ACTIVE = 135°. Flexion PASSIVE = 145°."},
  {c:"23",l:"Chap. 2.3",q:"Le LCA se tend principalement lors de :",o:["La flexion du genou","La rotation médiale","L'extension du genou","La rotation latérale"],a:2,e:"LCA se tend en EXTENSION. LCP est sollicité en FLEXION."},
  {c:"23",l:"Chap. 2.3",q:"Qu'est-ce que le kyste de Baker ?",o:["Une bourse prépatellaire inflammatoire","La bourse poplitée distendue par épanchement","Un kyste osseux du condyle","Une bourse infrapatellaire enflammée"],a:1,e:"Kyste de Baker = bourse POPLITÉE distendue par épanchement articulaire. Visible en fosse poplitée."},
  {c:"23",l:"Chap. 2.3",q:"Le LCM limite :",o:["Le varus + rotation médiale","Le valgus + rotation latérale","Le valgus + rotation médiale","Le varus + rotation latérale"],a:1,e:"LCM : limite le VALGUS + rotation LATÉRALE. LCL : limite le VARUS + rotation MÉDIALE."},

  // CHAPITRE 2.5
  {c:"25",l:"Chap. 2.5",q:"Lequel de ces muscles est innervé par un nerf DIFFÉRENT des autres ?",o:["Le psoas","Le sartorius","Le vaste intermédiaire","Le droit fémoral"],a:0,e:"PSOAS = branches directes plexus lombaire L1–L3. Sartorius + vastes + droit fémoral = nerf FÉMORAL."},
  {c:"25",l:"Chap. 2.5",q:"Lequel de ces muscles ne fait pas partie de la patte d'oie superficielle ?",o:["Semi-tendineux","Semi-membraneux","Gracile","Sartorius"],a:1,e:"SEMI-MEMBRANEUX = patte d'oie PROFONDE. Superficielle = Sartorius + Gracile + Semi-tendineux."},
  {c:"25",l:"Chap. 2.5",q:"Lequel des structures suivantes ne fait PAS partie des limites du triangle de Scarpa ?",o:["Le ligament inguinal","Le sartorius","Le grand adducteur","Le long adducteur"],a:2,e:"Triangle de Scarpa : limite sup. = lig. inguinal · lat. = sartorius · méd. = LONG adducteur. Grand adducteur n'est PAS une limite."},
  {c:"25",l:"Chap. 2.5",q:"Laquelle des affirmations sur les limites de la fosse poplitée est FAUSSE ?",o:["Au-dessus et latéral = le semi-membraneux","En dessous et latéral = le gastrocnémien latéral","En dessous et médial = le gastrocnémien médial","Au-dessus et médial = le semi-tendineux"],a:0,e:"FAUX : au-dessus et LATÉRAL = le BICEPS FÉMORAL (pas le semi-membraneux qui est médial)."},
  {c:"25",l:"Chap. 2.5",q:"Lequel de ces muscles ne s'insère pas sur la ligne âpre ?",o:["Le semi-membraneux","Le vaste externe","Le grand adducteur","L'un des chefs du biceps fémoral"],a:0,e:"Le SEMI-MEMBRANEUX s'insère sur le condyle MÉDIAL du tibia (pas sur la ligne âpre)."},
  {c:"25",l:"Chap. 2.5",q:"La partie postérieure de la cuisse est innervée par :",o:["Le nerf fémoral","Le nerf obturateur","Le nerf cutané postérieur cuisse","Le nerf sciatique"],a:3,e:"Zone POST. cuisse = nerf SCIATIQUE. Zone ant. = fémoral. Zone méd. = obturateur."},
  {c:"25",l:"Chap. 2.5",q:"Le contenu du canal des adducteurs (de Hunter) est :",o:["Artère + veine + nerf fémoral","Artère + veine fémorale + nerf saphène","Artère poplitée + veine poplitée + nerf tibial","Artère + veine fémorale + nerf obturateur"],a:1,e:"Canal Hunter : artère fémorale + veine fémorale + nerf SAPHÈNE."},
  {c:"25",l:"Chap. 2.5",q:"Le grand adducteur a 2 faisceaux avec 2 innervations différentes :",o:["Faisceau add. : nerf fémoral · Faisceau chond. : obturateur","Faisceau add. : nerf sciatique · Faisceau chond. : obturateur","Faisceau add. : nerf obturateur · Faisceau chond. : nerf sciatique","Les deux faisceaux : nerf sciatique"],a:2,e:"Grand add. : faisceau ADDUCTEUR = nerf obturateur · faisceau CHONDYLIEN = nerf SCIATIQUE."},
  {c:"25",l:"Chap. 2.5",q:"Lequel a son insertion la plus postérieure sur l'ischion ?",o:["Le semi-tendineux","Le semi-membraneux","Le biceps fémoral","Le grand fessier"],a:1,e:"SEMI-MEMBRANEUX a son insertion la plus postérieure sur la tubérosité ischiatique."},

  // CHAPITRE 2.6
  {c:"26",l:"Chap. 2.6",q:"Le court fibulaire et le long fibulaire peuvent faire une pronation du pied ?",o:["Vrai","Faux"],a:0,e:"VRAI. Court fibulaire = pronation + abduction. Long fibulaire = flexion plantaire + abduction + PRONATION."},
  {c:"26",l:"Chap. 2.6",q:"Quelle est l'innervation des muscles du groupe latéral de la jambe ?",o:["Nerf fibulaire superficiel","Nerf fibulaire profond","Nerf tibial","Nerf sciatique"],a:0,e:"Groupe LATÉRAL (court + long fibulaire) = nerf FIBULAIRE SUPERFICIEL."},
  {c:"26",l:"Chap. 2.6",q:"Le muscle poplité fait une rotation externe du genou ?",o:["Vrai","Faux"],a:1,e:"FAUX. Poplité = rotation INTERNE (déverrouillage genou)."},
  {c:"26",l:"Chap. 2.6",q:"Lequel des muscles suivants ne s'insère pas sur le tendon d'Achille ?",o:["Le gastrocnémien","Le soléaire","Les deux s'insèrent sur ce tendon","Les deux ne s'insèrent pas"],a:2,e:"Gastrocnémien ET soléaire s'insèrent TOUS LES DEUX sur le tendon d'Achille (calcanéen)."},
  {c:"26",l:"Chap. 2.6",q:"À quel muscle appartient cette insertion : naviculaire + cuboïde + cunéiforme + base 2e–4e métatarsien ?",o:["Court fibulaire","Long fibulaire","Tibial antérieur","Tibial postérieur"],a:3,e:"TIBIAL POSTÉRIEUR. Action : INVERSION du pied."},
  {c:"26",l:"Chap. 2.6",q:"Dans la gouttière latérale du pied, le court fibulaire est en avant du long fibulaire ?",o:["Vrai","Faux"],a:0,e:"VRAI. Dans la gouttière rétromalléolaire : court fibulaire est en AVANT du long fibulaire."},
  {c:"26",l:"Chap. 2.6",q:"Laquelle des articulations suivantes est une syndesmose ?",o:["Cubo-naviculaire","Cuboïdo-cunéiforme","Naviculaire-cunéiforme","Calcanéo-cuboïdienne"],a:0,e:"CUBO-NAVICULAIRE = syndesmose. Autres inter-tarsiennes = arthrodies. Calcanéo-cuboïdienne = en selle."},
  {c:"26",l:"Chap. 2.6",q:"De quel type est l'articulation sous-talienne ?",o:["Trochoïde","Trochléenne","Condylienne","Arthrodie"],a:0,e:"Articulation sous-talienne = TROCHOÏDE. Axe sous-talien = axe de Henke."},
  {c:"26",l:"Chap. 2.6",q:"L'éversion est une combinaison de :",o:["Flex. plantaire + adduction + supination","Flex. dorsale + abduction + supination","Flex. plantaire + adduction + pronation","Flex. dorsale + abduction + pronation"],a:3,e:"ÉVERSION = flex. dorsale + abduction + PRONATION. INVERSION = flex. plantaire + adduction + supination."},
  {c:"26",l:"Chap. 2.6",q:"Lequel des éléments n'est PAS relié avec le ligament bifurqué (de Chopart) ?",o:["Cuboïde","Naviculaire","Talus","Calcanéum"],a:2,e:"Lig. bifurqué = CALCANÉUM → CUBOÏDE + NAVICULAIRE. Le TALUS n'y est pas relié."},
  {c:"26",l:"Chap. 2.6",q:"Le rétinaculum des extenseurs inférieur a une forme de :",o:["Bande droite","Croix","Y","Anneau"],a:2,e:"Rétinaculum ext. INF. = forme de Y. Pointe = calcanéum. Bras sup. = malléole interne. Bras inf. = aponévrose plantaire."},
  {c:"26",l:"Chap. 2.6",q:"La trochlée talaire est plus large :",o:["En arrière","Sur sa face médiale","Sur sa face latérale","En avant"],a:3,e:"Trochlée talaire = plus large EN AVANT. En flex. dorsale le talus se cale dans la mortèse = très stable."},
  {c:"26",l:"Chap. 2.6",q:"La flexion dorsale est limitée par :",o:["Lig. talo-fibulaire ant. + faisceaux ant. deltoïde","Les muscles fibulaires","Lig. talo-fibulaire post. + faisceaux post. deltoïde","Le lig. calcanéo-fibulaire"],a:2,e:"Freins FLEX. DORSALE : lig. talo-fibulaire POST. + faisceaux POST. deltoïde."},

  // CHAPITRE 2.7
  {c:"27",l:"Chap. 2.7",q:"Les muscles interosseux dorsaux font :",o:["Fléchissent les orteils et les déplacent latéralement","Étendent les orteils et les déplacent latéralement","Fléchissent les orteils et les déplacent médialement","Étendent les orteils et les déplacent médialement"],a:0,e:"Interosseux DORSAUX : fléchissent + déplacent LATÉRALEMENT. PLANTAIRES : fléchissent + déplacent médialement."},
  {c:"27",l:"Chap. 2.7",q:"Quel muscle fait partie du groupe central MOYEN ?",o:["Les interosseux plantaires","Le carré plantaire","Court fléchisseur des orteils","Adducteur de l'hallux"],a:1,e:"Groupe central MOYEN = carré plantaire + lombricaux. Plan PROFOND = interosseux. Plan SUPERFICIEL = court fléch. orteils."},
  {c:"27",l:"Chap. 2.7",q:"L'abducteur de l'hallux est innervé par :",o:["Le nerf tibial","Le nerf fibulaire","Les nerfs plantaires médial et fibulaire","Les nerfs plantaires latéral et médial"],a:3,e:"Abducteur hallux = nerfs plantaires LATÉRAL ET MÉDIAL (innervation mixte)."},
  {c:"27",l:"Chap. 2.7",q:"Le court fléchisseur des orteils s'insère sur :",o:["Phalange distale 2e–5e","Phalange proximale 2e–5e","Phalange moyenne 2e–5e via tendons perforés","Base des métatarsiens"],a:2,e:"Court fléch. orteils → phalange MOYENNE via TENDONS PERFORÉS. Nerf plantaire MÉDIAL."},
  {c:"27",l:"Chap. 2.7",q:"Combien y a-t-il d'interosseux dorsaux dans le pied ?",o:["2","3","4","5"],a:2,e:"Interosseux DORSAUX = 4 muscles. Interosseux PLANTAIRES = 3 muscles."},
  {c:"27",l:"Chap. 2.7",q:"L'adducteur de l'hallux possède 2 têtes. La tête transversale origine sur :",o:["Bases 2e–5e métatarsiens + cunéiforme lat.","Face inférieure calcanéum","3e–5e articulations métatarso-phalangiennes","Cuboïde + cunéiforme latéral"],a:2,e:"Tête TRANSVERSALE : 3e–5e articulations MP. Tête OBLIQUE : bases 2e–5e métatarsiens + cunéif. lat. + cuboïde."},
  {c:"27",l:"Chap. 2.7",q:"L'aponévrose plantaire principale a une forme :",o:["Rectangulaire","Triangulaire","Ovale","Circulaire"],a:1,e:"Aponévrose plantaire = TRIANGULAIRE. Calcanéum en post. → 5 fascicules vers les orteils."},
  {c:"27",l:"Chap. 2.7",q:"Le court extenseur de l'hallux est innervé par :",o:["Nerf plantaire médial","Nerf tibial","Nerf fibulaire superficiel","Nerf fibulaire profond"],a:3,e:"Court ext. hallux = nerf FIBULAIRE PROFOND (comme tout le groupe dorsal du pied)."},
  {c:"27",l:"Chap. 2.7",q:"L'opposant du 5e orteil réalise :",o:["Flexion + abduction 5e","Flexion + adduction 5e","Abduction + extension 5e","Flexion seule 5e"],a:1,e:"Opposant 5e : flexion + ADDUCTION. Abducteur 5e : flexion + ABDUCTION."},

  // CHAPITRE 2.8
  {c:"28",l:"Chap. 2.8",q:"Le plexus lombaire est formé par :",o:["Branches ant. L1–L5","Branches ant. L1–L4","Branches ant. L2–L5","Branches ant. L1–S1"],a:1,e:"Plexus lombaire = branches antérieures de L1 à L4. Situé dans l'épaisseur du PSOAS."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf saphène est :",o:["Une branche du nerf obturateur","Une branche sensitive du nerf fémoral","Une branche du nerf sciatique","Une branche du nerf tibial"],a:1,e:"Nerf saphène = branche terminale SENSITIVE du nerf FÉMORAL. Descend dans le canal de Hunter."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf obturateur sort du bassin par :",o:["Le grand foramen sciatique","Le petit foramen sciatique","Le trou obturé","Le foramen sacré"],a:2,e:"Nerf obturateur : naît bord MÉD. psoas → sort par le TROU OBTURÉ."},
  {c:"28",l:"Chap. 2.8",q:"Le plexus sacré est situé :",o:["Dans l'épaisseur du piriforme","Au-dessus du muscle piriforme","En dessous du muscle piriforme","Dans le canal obturateur"],a:1,e:"Plexus sacré = paroi pelvienne postérieure, AU-DESSUS du piriforme."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf fessier supérieur innerve :",o:["Grand glutéal uniquement","Moyen + petit glutéal + TFL","Piriforme + obturateur interne","Grand + moyen glutéal + TFL"],a:1,e:"N. fessier SUPÉRIEUR : moyen glutéal + petit glutéal + TFL. N. fessier INFÉRIEUR : grand glutéal."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf fibulaire commun entoure :",o:["La malléole latérale","La tête de la fibula","La malléole médiale","Le col du talus"],a:1,e:"Nerf fibulaire commun entoure la TÊTE de la fibula → fibulaire superficiel + profond."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf fibulaire profond innerve la zone :",o:["Latérale de la jambe","Postérieure de la jambe","Antérieure de la jambe","Médiale de la jambe"],a:2,e:"Fibulaire PROFOND = zone ANTÉRIEURE jambe."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf plantaire médial innerve en sensitif :",o:["5e orteil + moitié lat. 4e","3 orteils et demi médiaux","Toute la plante du pied","2 orteils médiaux uniquement"],a:1,e:"N. plantaire MÉDIAL sensitif : 3 orteils et demi MÉDIAUX. N. plantaire LATÉRAL sensitif : 5e + moitié lat. 4e."},
  {c:"28",l:"Chap. 2.8",q:"Dans la cuisse, la zone médiale est innervée par :",o:["Nerf fémoral","Nerf obturateur","Nerf sciatique","Nerf cutané fémoral latéral"],a:1,e:"Cuisse : ANT = nerf FÉMORAL · POST = nerf SCIATIQUE · MÉD = nerf OBTURATEUR."},
  {c:"28",l:"Chap. 2.8",q:"Le tronc lombo-sacré est formé par :",o:["L4 + L5 entiers","Branche ant. L5 + branche communicante de L4","L4 + S1","Branche ant. L4 + branche communicante de L5"],a:1,e:"Tronc lombo-sacré = branche ant. L5 + branche communicante de L4."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf cutané fémoral latéral est issu de :",o:["L1–L2","L2–L3","L3–L4","L1–L3"],a:1,e:"N. cutané fémoral LATÉRAL = L2–L3. Sensitif face LATÉRALE de la cuisse."},
  {c:"28",l:"Chap. 2.8",q:"Quelle est la différence entre nerf fessier supérieur et inférieur ?",o:["Sup = grand glutéal / Inf = moyen + petit glutéal + TFL","Sup = moyen + petit glutéal + TFL / Inf = grand glutéal","Les deux innervent tous les glutéaux","Sup = piriforme / Inf = grand glutéal"],a:1,e:"N. fessier SUP. = moyen glutéal + petit glutéal + TFL. N. fessier INF. = grand glutéal UNIQUEMENT."}
];

// QUESTIONS SUPPLÉMENTAIRES
var EXTRA_Q = [
  // CHAPITRE 1 extra
  {c:"1",l:"Chap. 1",q:"La vertèbre C7 se distingue des autres vertèbres cervicales car :",o:["Elle n'a pas de processus transverse","Son processus épineux est le plus long et non bifide","Elle s'articule avec la 1ère côte","Elle présente un corps vertébral absent"],a:1,e:"C7 = vertèbre proéminente. Son processus épineux est le plus LONG et NON BIFIDE, contrairement aux autres cervicales."},
  {c:"1",l:"Chap. 1",q:"L'articulation sacro-iliaque est de type :",o:["Énarthrose","Symphyse","Amphiarthrose (synoviale plane + syndesmose)","Trochoïde"],a:2,e:"Articulation sacro-iliaque = AMPHIARTHROSE : partie antérieure = synoviale plane + partie postérieure = syndesmose."},
  {c:"1",l:"Chap. 1",q:"Les côtes dites 'fausses' sont les côtes :",o:["1 à 7","8 à 12","8 à 10","11 et 12"],a:2,e:"Côtes FAUSSES = 8, 9, 10 (s'articulent avec le sternum via les cartilages des côtes supérieures). Côtes flottantes = 11, 12."},
  {c:"1",l:"Chap. 1",q:"La symphyse pubienne est une :",o:["Synchondrose","Symphyse (fibrocartilage)","Synoviale plane","Syndesmose"],a:1,e:"Symphyse pubienne = SYMPHYSE avec un disque fibrocartilagineux entre les deux os pubiens."},
  {c:"1",l:"Chap. 1",q:"Le ligament longitudinal antérieur de la colonne :",o:["Limite la flexion","Limite l'extension","Limite la rotation","Limite l'inclinaison"],a:1,e:"Lig. longitudinal ANTÉRIEUR : se tend en EXTENSION -> limite l'extension. Lig. longitudinal POST. : limite la flexion."},
  // CHAPITRE 2 extra
  {c:"2",l:"Chap. 2",q:"L'os ethmoïde fait partie de :",o:["Uniquement du neurocrane","Uniquement du splanchnocrâne","Du neurocrane et du splanchnocrâne","Ni du neurocrane ni du splanchnocrâne"],a:2,e:"L'ethmoïde fait partie des DEUX : neurocrane (lame criblée) et splanchnocrâne (lame perpendiculaire et cornets)."},
  {c:"2",l:"Chap. 2",q:"Le foramen ovale de la base du crâne laisse passer :",o:["Le nerf optique (II)","Le nerf mandibulaire (V3)","L'artère méningée moyenne","Le nerf facial (VII)"],a:1,e:"Foramen ovale = nerf MANDIBULAIRE (V3). Foramen épineux = artère méningée moyenne. Canal optique = nerf optique."},
  {c:"2",l:"Chap. 2",q:"Le bregma est :",o:["La jonction des sutures lambdoïde et sagittale","La jonction des sutures coronale et sagittale","La jonction de 4 os : frontal, pariétal, sphénoïde, temporal","La jonction des sutures sagittale et temporale"],a:1,e:"BREGMA = jonction sutures CORONALE + SAGITTALE. Lambda = coronale + lambdoïde. Ptérion = jonction 4 os (temporal, pariétal, frontal, sphénoïde)."},
  {c:"2",l:"Chap. 2",q:"L'os hyoïde est unique car :",o:["C'est le seul os sans cartilage","C'est le seul os du corps qui ne s'articule avec aucun autre os","Il est entièrement cartilagineux","Il s'articule uniquement avec le temporal"],a:1,e:"L'os hyoïde est le seul os du corps qui ne s'articule avec AUCUN AUTRE OS. Il est maintenu par des muscles et ligaments."},
  {c:"2",l:"Chap. 2",q:"Quel os forme la plus grande partie du palais osseux ?",o:["Os palatin","Os maxillaire","Os sphénoïde","Os vomer"],a:1,e:"Le palais osseux est formé à 75% par l'OS MAXILLAIRE (palatins antérieurs) et 25% par les os palatins (partie postérieure)."},
  // CHAPITRE 3 extra
  {c:"3",l:"Chap. 3",q:"Le nerf grand occipital d'Arnold est :",o:["Branche motrice de C1","Branche sensitive de C2","Branche motrice de C2","Branche sensitive de C1"],a:1,e:"Nerf grand occipital d'Arnold = branche SENSITIVE de C2. Innerve le cuir chevelu postérieur."},
  {c:"3",l:"Chap. 3",q:"L'oblique supérieur de la tête réalise :",o:["Rotation homolatérale uniquement","Extension + rotation homolatérale","Extension + inclinaison","Flexion + inclinaison"],a:2,e:"Oblique SUP. : apoph. transv. atlas -> occipital. Action : extension + INCLINAISON."},
  {c:"3",l:"Chap. 3",q:"L'action du grand dorsal sur l'humérus est :",o:["Flexion + abduction + rotation latérale","Extension + adduction + rotation médiale","Extension + abduction + rotation médiale","Flexion + adduction + rotation latérale"],a:1,e:"Grand dorsal sur humérus : extension + ADDUCTION + rotation MÉDIALE."},
  {c:"3",l:"Chap. 3",q:"Le semi-épineux se distingue des multifides par :",o:["Un saut de 1 à 2 vertèbres","Un saut de 3 à 4 vertèbres","Un saut de plus de 4 vertèbres (6–8)","Aucune différence"],a:2,e:"Semi-épineux = saut de plus de 4 vertèbres (6–8). Multifides = 3–4. Rotateurs = 1–2."},
  {c:"3",l:"Chap. 3",q:"Le rhomboïde mineur prend origine sur :",o:["Épi. T2–T5","Lig. nucal inf. + épi. C7–T1","Apoph. transv. C1–C4","Lig. nucal sup. + occipital"],a:1,e:"Rhomboïde MINEUR : lig. nucal inf. + épi. C7–T1 -> bord méd. scapula (1/3 sup.)."},
  // CHAPITRE 4 extra
  {c:"4",l:"Chap. 4",q:"Le droit latéral de la tête réalise :",o:["Flexion + rotation homolatérale","Inclinaison de la tête uniquement","Extension + rotation homolatérale","Rotation controlatérale"],a:1,e:"Droit latéral : apoph. transv. atlas C1 -> face jugulaire occipital. Action : INCLINAISON tête uniquement."},
  {c:"4",l:"Chap. 4",q:"L'omohyoïdien origine sur :",o:["Le corps du sternum","Le bord supérieur de la scapula","Le cartilage thyroïde","La clavicule"],a:1,e:"Omohyoïdien : bord SUP. SCAPULA -> hyoïde. Seul infra-hyoïdien ne partant pas du sternum."},
  {c:"4",l:"Chap. 4",q:"Le long de la tête s'insère sur :",o:["L'apophyse transverse de C1","La partie basilaire de l'os occipital","Le tubercule antérieur de l'atlas","La ligne nucale supérieure"],a:1,e:"Long de la tête : apoph. transv. C3–C6 -> partie BASILAIRE occipital. Action : flexion + inclinaison homolatérale."},
  {c:"4",l:"Chap. 4",q:"Le stylohyoïdien est innervé par :",o:["Nerf trijumeau (V)","Nerf facial (VII)","Anse cervicale","Nerf hypoglosse (XII)"],a:1,e:"Stylohyoïdien = nerf FACIAL (VII). Comme le ventre postérieur du digastrique."},
  {c:"4",l:"Chap. 4",q:"Le géniohyoïdien est innervé par C1 qui chemine avec :",o:["Le nerf trijumeau (V)","Le nerf facial (VII)","Le nerf hypoglosse (XII)","L'anse cervicale"],a:2,e:"Géniohyoïdien : C1 chemine avec le nerf HYPOGLOSSE (XII). Action : élève l'hyoïde vers l'avant."},
  // CHAPITRE 5 extra
  {c:"5",l:"Chap. 5",q:"Le ptérygoïdien médial s'insère sur :",o:["Face latérale branche mandibule","Face médiale branche mandibule","Apophyse coronoïde","Col mandibule"],a:1,e:"Ptérygoïdien MÉDIAL -> face MÉDIALE branche mandibule. (Ptéryg. latéral -> col mandibule + disque)."},
  {c:"5",l:"Chap. 5",q:"Le ligament sphéno-mandibulaire fait partie de :",o:["La capsule articulaire ATM","Le fascia interptérygoïdien","Le ligament collatéral fibulaire","L'aponévrose temporale"],a:1,e:"Lig. sphéno-mand. : sphénoïde -> face méd. branche mandibulaire. Fait partie du FASCIA INTERPTÉRYGOÏDIEN."},
  {c:"5",l:"Chap. 5",q:"Le mouvement de latéralité de l'ATM se fait autour de :",o:["Un axe transversal passant par les 2 condyles","Un axe vertical passant par un seul condyle","Un axe sagittal passant par la symphyse","Un axe oblique"],a:1,e:"Latéralité = axe VERTICAL passant par UN condyle. Le menton se déplace du côté opposé."},
  {c:"5",l:"Chap. 5",q:"Lors de la rétropulsion, quel muscle est principalement en action ?",o:["Ptérygoïdien latéral","Fibres antérieures du temporal","Fibres postérieures du temporal","Masséter"],a:2,e:"Rétropulsion = fibres POSTÉRIEURES du temporal. Elles tirent le condyle et le ménisque vers l'arrière."},
  // THEME 6 extra
  {c:"6",l:"Thème 6",q:"Le transverse thoracique (triangulaire du sternum) s'insère sur :",o:["Face ant. cartilages costaux 2e–6e","Face post. cartilages costaux 2e–6e","Bord inf. côtes 2e–6e","Face ext. sternum"],a:1,e:"Transverse thoracique : face post. sternum + xiphoïde -> face POST. cartilages costaux 2e–6e. Abaisse -> expiration."},
  {c:"6",l:"Thème 6",q:"Le dentelé postérieur inférieur prend origine sur :",o:["Épi. T6–T10","Épi. T8–L1","Épi. T11–L3","Épi. T9–L2"],a:2,e:"Dentelé post. INF. : épi. T11–L3 -> bord sup. côtes IX–XII. Abaisse -> expiration."},
  {c:"6",l:"Thème 6",q:"L'amplitude de la flexion dorsale de cheville est limitée par :",o:["Lig. talo-fibulaire ant. + faisceaux ant. deltoïde","Lig. talo-fibulaire post. + faisceaux post. deltoïde","Le lig. calcanéo-fibulaire","Les muscles extenseurs"],a:1,e:"Freins FLEX. DORSALE : lig. talo-fibulaire POST. + faisceaux POST. deltoïde. En forcé : col du talus -> contact tibia."},
  {c:"6",l:"Thème 6",q:"Le mouvement en levier de pompe concerne :",o:["Les côtes inférieures","Les côtes supérieures","Toutes les côtes","Le diaphragme"],a:1,e:"Côtes SUPÉRIEURES = levier de pompe (élévation antéropostérieure). Côtes inférieures = anse de seau (élévation latérale)."},
  {c:"6",l:"Thème 6",q:"Les élévateurs des côtes sont innervés par :",o:["Nerfs intercostaux","Anse cervicale C1–C3","Branches postérieures des nerfs rachidiens","Nerf phrénique C3–C5"],a:2,e:"Élévateurs des côtes = branches POSTÉRIEURES des nerfs rachidiens (contrairement aux intercostaux = branches antérieures)."},
  // CHAPITRE 7 extra
  {c:"7",l:"Chap. 7",q:"Le pyramidal s'insère sur :",o:["La crête pubienne","L'apophyse xiphoïde","La ligne blanche","Le cartilage costal du 5e"],a:2,e:"Pyramidal : pubis -> LIGNE BLANCHE. Action : tend la ligne blanche. Innervé par T12. Muscle inconstant."},
  {c:"7",l:"Chap. 7",q:"L'oblique externe prend origine sur :",o:["Face interne côtes 5e–12e + apoph. transv.","Face externe côtes 5e–12e","Crête iliaque + lig. inguinal","Face interne des 6 dernières côtes"],a:1,e:"Oblique externe : face EXTERNE côtes 5e–12e. S'interdigite avec grand dorsal + dentelé antérieur."},
  {c:"7",l:"Chap. 7",q:"L'anneau inguinal superficiel se situe dans :",o:["L'aponévrose du transverse","L'aponévrose de l'oblique externe au-dessus du tubercule pubien","L'aponévrose de l'oblique interne","La gaine du droit"],a:1,e:"Anneau inguinal superficiel = orifice dans aponévrose OBLIQUE EXTERNE, au-dessus du tubercule pubien."},
  {c:"7",l:"Chap. 7",q:"Le carré des lombes en contraction unilatérale réalise :",o:["Rotation homolatérale colonne lombaire","Flexion colonne lombaire","Inclinaison homolatérale colonne lombaire","Extension colonne lombaire"],a:2,e:"Carré des lombes unilatéral = INCLINAISON HOMOLATÉRALE de la colonne lombaire."},
  {c:"7",l:"Chap. 7",q:"Le grand droit de l'abdomen prend origine sur :",o:["Cartilages costaux 5e–7e + xiphoïde","Crête pubienne","Ligne blanche","Symphyse pubienne"],a:1,e:"Grand droit : O = CRÊTE PUBIENNE -> I = cartilages costaux 5e–7e + xiphoïde. Ne pas inverser !"},
  // CHAPITRE 8 extra
  {c:"8",l:"Chap. 8",q:"L'élévateur de l'anus prend origine sur :",o:["Pubis post. + arc tendineux fascia obturateur + épine sciatique","Ischion + sacrum + coccyx","Pubis + membrane obturatrice","Sacrum + coccyx + épine ischiatique"],a:0,e:"Élévateur de l'anus : pubis post. + arc tendineux fascia obturateur interne + épine sciatique."},
  {c:"8",l:"Chap. 8",q:"L'obturateur interne est innervé par :",o:["Nerf obturateur L2–L4","Nerf obturateur interne L5–S1","Branches S2–S4","Nerf pudendal"],a:1,e:"Obturateur INTERNE = nerf obturateur interne L5–S1. À ne pas confondre avec nerf obturateur L2–L4 (adducteurs)."},
  {c:"8",l:"Chap. 8",q:"Le ligament large de l'utérus se compose de :",o:["Mésomètre + mésosalpinx + mésovarium","Lig. rond + lig. utéro-sacré + mésomètre","Mésovarium + lig. cardinal + mésosalpinx","Mésomètre + lig. pubo-cervical + mésovarium"],a:0,e:"Ligament large = mésomètre + mésosalpinx (trompe) + mésovarium (ovaire)."},
  {c:"8",l:"Chap. 8",q:"Le coccygien est innervé par :",o:["Nerf pudendal S2–S4","Branches ant. S3–S4","Branches ant. S4 uniquement","Nerf obturateur interne"],a:1,e:"Coccygien : branches antérieures de S3–S4. Élévateur de l'anus = branches ant. S4 + nerf pudendal S2–S4."},
  {c:"8",l:"Chap. 8",q:"Le bulbo-spongieux chez la femme réalise :",o:["Vidange résiduelle urètre","Déplace le sang vers le gland du clitoris","Ferme le canal anal","Stabilise le corps périnéal uniquement"],a:1,e:"Bulbo-spongieux ♀ : déplace le sang vers le GLAND du clitoris. ♂ : vidange urètre + émission sperme."},
  // CHAPITRE 9 extra
  {c:"9",l:"Chap. 9",q:"Combien y a-t-il de paires de nerfs cervicaux ?",o:["7","6","8","9"],a:2,e:"8 paires de nerfs cervicaux (C1–C8), bien que la colonne cervicale n'ait que 7 vertèbres."},
  {c:"9",l:"Chap. 9",q:"Le bord postérieur du foramen intervertébral est formé par :",o:["Le disque intervertébral","Les pédicules","Les processus articulaires + articulation zygapophysaire","Le ligament jaune"],a:2,e:"Bord POST. = processus articulaires + articulation ZYGAPOPHYSAIRE. Bord ant. = disque intervertébral."},
  {c:"9",l:"Chap. 9",q:"L'anesthésie péridurale injecte dans :",o:["L'espace sous-arachnoïdien","L'espace épidural","Entre dure-mère et arachnoïde","Le canal central"],a:1,e:"PÉRIDURALE = espace ÉPIDURAL. Rachianesthésie = espace sous-arachnoïdien."},
  {c:"9",l:"Chap. 9",q:"Les branches antérieures des nerfs rachidiens sont :",o:["Plus petites que les branches post.","Égales aux branches post.","Plus grandes et innervent la plupart du corps","Uniquement sensitives"],a:2,e:"Branches ANTÉRIEURES = beaucoup plus grandes. Forment les plexus. Branches post. = petites, innervent le dos."},
  {c:"9",l:"Chap. 9",q:"Le crémaster est innervé par :",o:["Nerf ilio-inguinal","Nerf génito-fémoral","Nerf ilio-hypogastrique","Nerf obturateur"],a:1,e:"Crémaster = nerf GÉNITO-FÉMORAL (L1–L2). Responsable du réflexe crémastérien."},
  // CHAPITRE 2.2 extra
  {c:"22",l:"Chap. 2.2",q:"L'amplitude de la rotation latérale de hanche est :",o:["20°","35°","60°","45°"],a:2,e:"Rotation LATÉRALE hanche = 60°. Rotation MÉDIALE = 35°. Flexion = 120°. Extension = 20°. Abduction = 40°."},
  {c:"22",l:"Chap. 2.2",q:"Le TFL (tenseur du fascia lata) prend origine sur :",o:["La crête iliaque","L'épine iliaque antéro-supérieure (EIAS)","L'épine iliaque antéro-inférieure (EIAI)","Le grand trochanter"],a:1,e:"TFL : EIAS -> condyle lat. tibia via tractus ilio-tibial. Action : abduction + flexion hanche."},
  {c:"22",l:"Chap. 2.2",q:"Le labrum acétabulaire est composé de :",o:["Cartilage hyalin","Fibrocartilage","Os spongieux","Tissu conjonctif dense"],a:1,e:"Labrum acétabulaire = FIBROCARTILAGE. Augmente la surface articulaire et la stabilité."},
  {c:"22",l:"Chap. 2.2",q:"Le ligament de la tête fémorale (ligament rond) avant la puberté a comme fonction principale :",o:["Stabiliser la tête fémorale","Assurer l'apport sanguin à la tête fémorale","Limiter l'adduction de hanche","Maintenir la congruence articulaire"],a:1,e:"Avant puberté : lig. tête fémorale = apport VASCULAIRE à la tête fémorale. Adulte = stabilisateur secondaire."},
  {c:"22",l:"Chap. 2.2",q:"Les muscles réalisant la rotation médiale de hanche sont :",o:["Fibres ant. petit + moyen glutéal + TFL","Grand glutéal + carré fémoral + obturateurs","Piriforme + jumeaux + obturateur ext.","Moyen glutéal seul"],a:0,e:"Rotation MÉDIALE : fibres ANT. petit glutéal + fibres ANT. moyen glutéal + TFL."},
  // CHAPITRE 2.3 extra
  {c:"23",l:"Chap. 2.3",q:"Le mécanisme de vissage (screw-home) du genou :",o:["Verrouille en flexion par rotation lat. automatique","Verrouille en extension par rotation lat. automatique tibia","Déverrouille par le quadriceps","Verrouille en extension par rotation méd. automatique"],a:1,e:"Screw-home : extension terminale -> rotation LATÉRALE automatique tibia -> genou verrouillé. Déverrouillage = poplité (rotation méd.)."},
  {c:"23",l:"Chap. 2.3",q:"Le condyle fémoral médial, comparé au latéral, est :",o:["Plus large et plus court","Plus étroit et plus court","Plus large et plus long","Plus étroit et plus long"],a:3,e:"Condyle MÉD. = plus ÉTROIT et plus LONG que le latéral."},
  {c:"23",l:"Chap. 2.3",q:"Le ménisque médial est plus souvent lésé car :",o:["Il est plus vascularisé","Il adhère au LCM -> moins mobile","Il est plus petit","Il est plus convexe"],a:1,e:"Ménisque méd. adhère au LCM -> MOINS MOBILE -> plus souvent lésé lors de valgus forcé (triade malheureuse)."},
  {c:"23",l:"Chap. 2.3",q:"L'hyperextension active du genou est de :",o:["5°","15°","0° (impossible)","10°"],a:3,e:"Hyperextension ACTIVE = 10°. Hyperextension PASSIVE = 15°."},
  {c:"23",l:"Chap. 2.3",q:"Le plan profond (capsulaire) des ligaments antérieurs du genou comprend :",o:["Lig. patellaire + rétinaculum patellaire","Fascia lata + fascia jambier","Lig. fémoro-patellaires + lig. ménisco-patellaires","LCA + LCP"],a:2,e:"Plan PROFOND ant. = lig. fémoro-patellaires (ailerons) + lig. ménisco-patellaires."},
  // CHAPITRE 2.5 extra
  {c:"25",l:"Chap. 2.5",q:"Le droit fémoral prend origine sur :",o:["EIAS + face ant. corps fémoral","EIAI (tendon direct) + sillon supra-acétabulaire (tendon indirect)","Bord latéral ligne âpre + grand trochanter","Bord médial ligne âpre + ligne intertrochantérienne"],a:1,e:"Droit fémoral : tendon DIRECT = EIAI · tendon INDIRECT = sillon supra-acétabulaire. Seul chef biarticulaire."},
  {c:"25",l:"Chap. 2.5",q:"Le sartorius réalise sur la hanche :",o:["Flexion + adduction + rotation médiale","Extension + abduction + rotation latérale","Flexion + abduction + rotation latérale","Flexion + adduction + rotation latérale"],a:2,e:"Sartorius : hanche = flexion + ABDUCTION + rotation LATÉRALE. 'Muscle du tailleur'."},
  {c:"25",l:"Chap. 2.5",q:"La patte d'oie PROFONDE correspond à :",o:["Sartorius + Gracile + Semi-tendineux","Semi-membraneux (3 tendons)","Gracile + Semi-tendineux + Semi-membraneux","Sartorius + Semi-tendineux + Semi-membraneux"],a:1,e:"Patte d'oie PROFONDE = Semi-membraneux uniquement (3 tendons : direct + récurrent + réfléchi)."},
  {c:"25",l:"Chap. 2.5",q:"Le biceps fémoral réalise à la jambe :",o:["Flexion + rotation médiale","Flexion + rotation latérale","Extension + rotation médiale","Flexion uniquement"],a:1,e:"Biceps fémoral : hanche = extension · jambe = flexion + rotation LATÉRALE. Seul ischio-jambier à faire la rotation lat."},
  {c:"25",l:"Chap. 2.5",q:"Le pectiné est innervé par :",o:["Nerf obturateur L2–L4","Nerf sciatique","Nerf fémoral","Nerf fémoral + parfois obturateur"],a:2,e:"Pectiné = nerf FÉMORAL (exception dans la loge médiale). Les autres adducteurs = nerf obturateur."},
  // CHAPITRE 2.6 extra
  {c:"26",l:"Chap. 2.6",q:"Le tibial antérieur s'insère sur :",o:["Tubercule 5e métatarsien","Base 1er métatarsien uniquement","Face plantaire 1er cunéiforme + 1er métatarsien","Naviculaire + cunéiformes"],a:2,e:"Tibial ant. : face lat. tibia -> face plantaire 1er cunéiforme + 1er métatarsien. Flex. dorsale + adduction + supination."},
  {c:"26",l:"Chap. 2.6",q:"Le long fibulaire s'insère sur :",o:["Tubercule 5e métatarsien","Base 1er métatarsien","Naviculaire","Base 5e métatarsien"],a:1,e:"Long fibulaire -> BASE 1er métatarsien. Action : flex. plantaire + abduction + pronation."},
  {c:"26",l:"Chap. 2.6",q:"Le tibial postérieur réalise comme action principale :",o:["Éversion du pied","Flexion dorsale + abduction","Inversion du pied","Flexion plantaire uniquement"],a:2,e:"Tibial post. = INVERSION du pied. Nerf tibial."},
  {c:"26",l:"Chap. 2.6",q:"Le gastrocnémien est BIARTICULAIRE car il agit sur :",o:["La hanche et le genou","Le genou et la cheville","La cheville et le pied","La hanche et la cheville"],a:1,e:"Gastrocnémien : biarticulaire -> flex. plantaire CHEVILLE + flexion GENOU. Soléaire = monoarticulaire."},
  {c:"26",l:"Chap. 2.6",q:"Le rétinaculum fléchisseur s'étend de :",o:["Malléole lat. -> calcanéum","Malléole méd. -> calcanéum","Tibia -> fibula","Calcanéum -> naviculaire"],a:1,e:"Rétinaculum FLÉCHISSEUR : malléole MÉDIALE -> calcanéum. Maintient tendons muscles profonds face méd. cheville."},
  // CHAPITRE 2.7 extra
  {c:"27",l:"Chap. 2.7",q:"Les lombricaux du pied prennent origine sur :",o:["Face inférieure calcanéum","Tendons LFO (bords médiaux)","Base des métatarsiens","Cunéiformes et cuboïde"],a:1,e:"Lombricaux : tendons LFO (bords MÉDIAUX) -> base phalanges proximales 2e–5e orteils."},
  {c:"27",l:"Chap. 2.7",q:"L'adducteur de l'hallux s'insère via :",o:["Sésamoïde médial","Sésamoïde latéral","Directement sans sésamoïde","Les deux sésamoïdes"],a:1,e:"Adducteur hallux -> sésamoïde LATÉRAL. Abducteur hallux -> sésamoïde MÉDIAL."},
  {c:"27",l:"Chap. 2.7",q:"L'abducteur de l'hallux prend origine sur :",o:["Face inférieure calcanéum","Bases 2e–5e métatarsiens","Tubercule médial de la tubérosité calcanéenne","Cunéiformes et structures plantaires"],a:2,e:"Abducteur hallux : tubercule MÉD. de la tubérosité calcanéenne -> phalange proximale hallux via sésamoïde médial."},
  {c:"27",l:"Chap. 2.7",q:"Quelle est l'action de l'adducteur de l'hallux sur la voûte plantaire ?",o:["Soutient uniquement la voûte longitudinale","Soutient uniquement la voûte transversale","Soutient la voûte longitudinale ET transversale","N'a aucun rôle sur la voûte"],a:2,e:"Adducteur hallux = soutient voûte LONGITUDINALE ET TRANSVERSALE."},
  {c:"27",l:"Chap. 2.7",q:"Le carré plantaire s'insère sur :",o:["Tubercule médial calcanéum","Bord latéral du tendon LFO","Base phalanges proximales","Face plantaire naviculaire"],a:1,e:"Carré plantaire : face inf. calcanéum -> bord LATÉRAL tendon LFO. Nerf plantaire latéral."},
  // CHAPITRE 2.8 extra
  {c:"28",l:"Chap. 2.8",q:"Le nerf fémoral pénètre dans la cuisse :",o:["Médialement aux vaisseaux fémoraux","Latéralement aux vaisseaux fémoraux","En avant du lig. inguinal","Entre les vaisseaux fémoraux"],a:1,e:"Nerf fémoral : passe derrière le lig. inguinal + LATÉRALEMENT aux vaisseaux fémoraux (VAN : Veine + Artère + Nerf, de méd. à lat.)."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf sciatique innerve en branches directes :",o:["Quadriceps + sartorius","Chef long biceps + semi-tendineux + semi-membraneux + grand add. faisceau chond.","Adducteurs + gracile","Grand glutéal + piriforme"],a:1,e:"Sciatique direct : chef LONG biceps + semi-tendineux + semi-membraneux + grand add. faisceau CHONDYLIEN."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf tibial innerve la zone :",o:["Antérieure de la jambe","Latérale de la jambe","Postérieure de la jambe","Médiale de la jambe"],a:2,e:"Nerf TIBIAL = zone POSTÉRIEURE jambe (triceps sural + poplité + tibial post. + long fléch. orteils + hallux + plantaire)."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf plantaire latéral innerve en sensitif :",o:["3 orteils et demi médiaux","5e orteil + moitié lat. 4e orteil","Toute la plante du pied","2 orteils latéraux uniquement"],a:1,e:"N. plantaire LATÉRAL sensitif : 5e orteil + moitié lat. 4e orteil."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf génito-fémoral est issu de :",o:["L1 uniquement","L2–L3","L1–L2","L3–L4"],a:2,e:"N. génito-fémoral = L1–L2. Innerve le crémaster (moteur) + sensitif région inguinale."}
];

// SÉRIE 3 - 80 questions supplémentaires
var EXTRA_Q2 = [
  // CHAP 1
  {c:"1",l:"Chap. 1",q:"Le disque intervertébral est composé de :",o:["Nucleus pulposus au centre + anneau fibreux en périphérie","Anneau fibreux au centre + nucleus pulposus en périphérie","Uniquement de fibrocartilage","Uniquement de cartilage hyalin"],a:0,e:"Disque intervertébral : NUCLEUS PULPOSUS (gélatineux) au centre + ANNEAU FIBREUX (fibrocartilage) en périphérie."},
  {c:"1",l:"Chap. 1",q:"L'articulation atlanto-occipitale permet principalement :",o:["La rotation de la tête","La flexion/extension de la tête (oui/oui)","L'inclinaison uniquement","La rotation et l'inclinaison"],a:1,e:"Atlanto-occipitale (C0–C1) = articulation condylienne -> FLEXION/EXTENSION + légère inclinaison ('dire oui'). La rotation = atlanto-axiale (C1–C2)."},
  {c:"1",l:"Chap. 1",q:"Le ligament jaune relie :",o:["Les corps vertébraux","Les processus épineux","Les lames vertébrales adjacentes","Les processus transverses"],a:2,e:"Ligament JAUNE = entre les LAMES vertébrales adjacentes. Riche en fibres élastiques (jaune). Limite la flexion."},
  {c:"1",l:"Chap. 1",q:"La hernie discale la plus fréquente touche le niveau :",o:["C5–C6","T12–L1","L4–L5 et L5–S1","T10–T11"],a:2,e:"Hernies discales les plus fréquentes = L4–L5 et L5–S1 car ce sont les niveaux les plus sollicités mécaniquement."},
  {c:"1",l:"Chap. 1",q:"Le ligament nucal est :",o:["Un ligament inter-épineux cervical élargi","Le ligament longitudinal antérieur cervical","Un ligament transversaire cervical","Le ligament longitudinal postérieur cervical"],a:0,e:"Ligament nucal = ligament inter-épineux CERVICAL élargi. S'étend de la protubérance occipitale à C7."},
  // CHAP 2
  {c:"2",l:"Chap. 2",q:"Le ptérion est :",o:["La jonction des sutures sagittale et lambdoïde","La jonction de 4 os : temporal, pariétal, frontal, sphénoïde","La jonction des sutures coronale et sagittale","Un foramen de la base du crâne"],a:1,e:"PTÉRION = jonction de 4 os : temporal + pariétal + frontal + sphénoïde. Zone fragile car l'artère méningée moyenne passe dessous."},
  {c:"2",l:"Chap. 2",q:"L'os temporal présente :",o:["La fosse ptérygoïdienne","La fosse mandibulaire (glène temporale)","Le tubercule adducteur","La surface semi-lunaire"],a:1,e:"Os temporal présente la FOSSE MANDIBULAIRE (glène temporale) qui s'articule avec le condyle mandibulaire = ATM."},
  {c:"2",l:"Chap. 2",q:"La lame criblée de l'ethmoïde laisse passer :",o:["Le nerf optique","Le nerf olfactif (I)","Le nerf trijumeau","L'artère carotide interne"],a:1,e:"Lame criblée de l'ethmoïde = passage du nerf OLFACTIF (I). Nombreuses perforations pour les filets olfactifs."},
  // CHAP 3
  {c:"3",l:"Chap. 3",q:"Le dentelé postérieur supérieur prend origine sur :",o:["Épi. T11–L3","Lig. nucal inf. + épi. C7–T3","Épi. T6–T10","Apoph. transv. C7–T3"],a:1,e:"Dentelé post. SUP. : lig. nucal inf. + épi. C7–T3 -> bord inf. côtes II–V. Action INSPIRATOIRE."},
  {c:"3",l:"Chap. 3",q:"Le grand dorsal réalise sur l'humérus :",o:["Flexion + abduction + rotation latérale","Extension + adduction + rotation médiale","Extension + abduction + rotation médiale","Flexion + adduction + rotation latérale"],a:1,e:"Grand dorsal sur humérus : EXTENSION + ADDUCTION + rotation MÉDIALE."},
  {c:"3",l:"Chap. 3",q:"L'élévateur de la scapula s'insère sur :",o:["Épine de la scapula","Angle inférieur de la scapula","Bord médial supérieur de la scapula","Acromion"],a:2,e:"Élévateur scapula : apoph. transv. C1–C4 -> bord MÉDIAL SUPÉRIEUR de la scapula."},
  {c:"3",l:"Chap. 3",q:"Les rhomboïdes sont innervés par :",o:["Nerf thoracodorsal C6–C8","Nerf accessoire XI","Nerf dorsal de la scapula C4–C5","Plexus cervical C3–C4"],a:2,e:"Rhomboïdes = nerf dorsal de la SCAPULA C4–C5. Même innervation que l'élévateur de la scapula."},
  // CHAP 4
  {c:"4",l:"Chap. 4",q:"Le plexus cervical est formé par :",o:["Branches ant. C1–C4","Branches ant. C1–C5","Branches post. C1–C4","Branches ant. C2–C5"],a:0,e:"Plexus cervical = branches antérieures de C1 à C4. Donne le nerf phrénique (C3–C5), les nerfs cutanés du cou."},
  {c:"4",l:"Chap. 4",q:"L'anse cervicale innerve :",o:["Le trapèze et le SCM","Les muscles infra-hyoïdiens (sauf thyrohyoïdien)","Tous les muscles infra-hyoïdiens","Les muscles supra-hyoïdiens"],a:1,e:"Anse cervicale (C1–C3) innerve les muscles INFRA-HYOÏDIENS sauf le thyrohyoïdien (anse + XII)."},
  {c:"4",l:"Chap. 4",q:"Le sternohyoïdien prend origine sur :",o:["La face postérieure du sternum","Le sternum et la clavicule","L'apophyse xiphoïde","La cartilage thyroïde"],a:1,e:"Sternohyoïdien : sternum + clavicule -> hyoïde. Il abaisse l'hyoïde."},
  // CHAP 5
  {c:"5",l:"Chap. 5",q:"Le ptérygoïdien latéral prend origine sur :",o:["Fosse ptérygoïdienne entre les 2 lames","Grande aile sphénoïde + face lat. lame lat. apoph. ptérygoïde","Arcade zygomatique + fosse temporale","Plancher fosse temporale"],a:1,e:"Ptérygoïdien LATÉRAL : grande aile sphénoïde + face lat. lame LAT. apoph. ptérygoïde -> col mandibule + disque."},
  {c:"5",l:"Chap. 5",q:"Lors de l'élévation mandibulaire (fermeture bouche) :",o:["Le condyle avance seul","Le condyle et le disque reculent puis le condyle tourne","Le disque reste fixe et le condyle monte","Les ptérygoïdiens latéraux sont actifs"],a:1,e:"Élévation : condyle + disque RECULENT d'abord puis le condyle TOURNE sur la face inf. du ménisque. Muscles : temporal + masséter + ptéryg. méd."},
  {c:"5",l:"Chap. 5",q:"Le masséter et le ptérygoïdien médial forment ensemble :",o:["Le triangle interptérygoïdien","Une écharpe musculaire autour de l'angle mandibulaire","Le raphé ptérygomandibulaire","La fosse infra-temporale"],a:1,e:"Masséter (face lat.) + ptérygoïdien médial (face méd.) = écharpe musculaire autour de l'ANGLE MANDIBULAIRE."},
  // THEME 6
  {c:"6",l:"Thème 6",q:"Le hiatus aortique (T12) contient :",o:["Aorte uniquement","Aorte + canal thoracique + veine azygos","Aorte + nerfs vagues","Aorte + veine cave inférieure"],a:1,e:"T12 = aorte + CANAL THORACIQUE + veine AZYGOS. T10 = œsophage + nerfs vagues. T8 = veine cave."},
  {c:"6",l:"Thème 6",q:"Le diaphragme s'abaisse lors de :",o:["L'expiration","La toux uniquement","L'inspiration","Le hoquet"],a:2,e:"Diaphragme s'ABAISSE à l'INSPIRATION (augmente volume thoracique). S'élève à l'expiration."},
  {c:"6",l:"Thème 6",q:"L'insertion sternale du diaphragme se fait sur :",o:["Corps du sternum","Manubrium sternal","Apophyse xiphoïde","1ère côte + manubrium"],a:2,e:"Insertion STERNALE diaphragme = apophyse XIPHOÏDE."},
  {c:"6",l:"Thème 6",q:"Les intercostaux externes s'étendent :",o:["De l'angle costal au sternum","De la tête costale à l'angle costal","Du tubercule costal aux cartilages costaux","De l'angle costal à 5–6 cm du sternum"],a:2,e:"Intercostaux EXTERNES : tubercule costal -> cartilages costaux. Au-delà = membrane intercostale externe."},
  // CHAP 7
  {c:"7",l:"Chap. 7",q:"Le feuillet antérieur de la gaine du droit au-dessus de l'EIAS est formé par :",o:["Oblique ext. + ½ oblique int.","Les 3 aponévroses ensemble","½ oblique int. + transverse","Transverse + oblique ext."],a:0,e:"Feuillet ANT. au-dessus EIAS = oblique ext. + ½ oblique int. Feuillet POST. = ½ oblique int. + transverse."},
  {c:"7",l:"Chap. 7",q:"En dessous de l'EIAS, les 3 aponévroses forment :",o:["Les deux parois ant. et post.","Uniquement la paroi postérieure","La gaine complète du droit","Uniquement la paroi antérieure"],a:3,e:"En dessous EIAS = les 3 aponévroses passent toutes en AVANT -> uniquement paroi ANTÉRIEURE. Plus de paroi post."},
  {c:"7",l:"Chap. 7",q:"Quelles hernies peuvent se produire dans la ligne blanche ?",o:["Hernie inguinale et crurale","Hernie hiatale et fémorale","Hernie ombilicale et épigastrique","Hernie sciatique et obturatrice"],a:2,e:"Ligne blanche : hernies OMBILICALE et ÉPIGASTRIQUE. Hernies inguinales = canal inguinal."},
  {c:"7",l:"Chap. 7",q:"La paroi latérale du canal des adducteurs (de Hunter) est formée par :",o:["Le long adducteur","Le sartorius","Le grand adducteur","Le vaste médial"],a:3,e:"Canal Hunter : paroi ant.-int. = sartorius · paroi post. = long add. + grand add. · paroi LAT. = VASTE MÉDIAL."},
  // CHAP 8
  {c:"8",l:"Chap. 8",q:"Le fascia viscéral pelvien entoure :",o:["Les parois pelviennes","Les organes pelviens (= fascia endopelvien)","Les muscles du plancher","Le péritoine pariétal"],a:1,e:"Fascia VISCÉRAL = entoure les organes pelviens (= fascia endopelvien). Fascia PARIÉTAL = tapisse les parois."},
  {c:"8",l:"Chap. 8",q:"L'action principale de l'élévateur de l'anus chez la femme est :",o:["Uniquement soutenir les viscères","Soutenir viscères + élever plancher + sphincter vaginal","Uniquement maintenir l'angle recto-anal","Uniquement renforcer sphincter anal"],a:1,e:"Élévateur anus ♀ : soutient viscères + élève plancher + maintient angle recto-anal + renforce sphincter anal + SPHINCTER VAGINAL."},
  {c:"8",l:"Chap. 8",q:"Le transverse superficiel du périnée stabilise :",o:["La membrane périnéale","Le corps périnéal","La base du clitoris","Le fascia obturateur"],a:1,e:"Transverse superficiel : tubérosité ischiatique -> corps périnéal. Stabilise le CORPS PÉRINÉAL."},
  {c:"8",l:"Chap. 8",q:"Le nerf pudendal passe dans le canal :",o:["Obturateur","D'Alcock","De Hunter","Inguinal"],a:1,e:"Nerf pudendal passe dans le canal D'ALCOCK (canal pudendal) après être entré par le petit foramen sciatique."},
  // CHAP 9
  {c:"9",l:"Chap. 9",q:"Le LCR est produit par :",o:["Les méninges","Les plexus choroïdes des ventricules","L'épendyme uniquement","Les cellules gliales"],a:1,e:"Le LCR est produit par les PLEXUS CHOROÏDES dans les ventricules cérébraux."},
  {c:"9",l:"Chap. 9",q:"La dure-mère spinale forme les :",o:["Arachnoïdes","Gaines des nerfs rachidiens jusqu'au foramen intervertébral","Pie-mères","Plexus choroïdes"],a:1,e:"La dure-mère spinale forme les GAINES des nerfs rachidiens jusqu'au foramen intervertébral."},
  {c:"9",l:"Chap. 9",q:"Combien y a-t-il de paires de nerfs lombaires ?",o:["4","5","6","3"],a:1,e:"5 paires de nerfs lombaires (L1–L5). 8 cervicaux, 12 thoraciques, 5 lombaires, 5 sacrés, 1 coccygien."},
  {c:"9",l:"Chap. 9",q:"Le nerf XII (hypoglosse) innerve :",o:["Le trapèze + SCM","Les muscles masticateurs","Les muscles de la langue + thyrohyoïdien + géniohyoïdien","Les muscles mimique"],a:2,e:"NC XII = muscles de la LANGUE + thyrohyoïdien + géniohyoïdien. NC XI = trapèze + SCM."},
  {c:"9",l:"Chap. 9",q:"Le nerf V (trijumeau) réalise :",o:["Moteur muscles mimique + sensitif face","Sensitif face + moteur muscles masticateurs","Moteur trapèze + SCM","Moteur muscles langue"],a:1,e:"NC V = trijumeau : SENSITIF face + MOTEUR muscles masticateurs (branche mandibulaire V3)."},
  // CHAP 2.2
  {c:"22",l:"Chap. 2.2",q:"L'amplitude de l'abduction de hanche est de :",o:["30°","40°","50°","20°"],a:1,e:"Abduction hanche = 40°. Adduction = 30°. Mnémotechnique : Abd > Add (40 > 30)."},
  {c:"22",l:"Chap. 2.2",q:"Le grand glutéal s'insère via ses fibres SUPERFICIELLES sur :",o:["La crête du grand glutéal (ligne âpre)","Le tractus ilio-tibial","Le petit trochanter","La tubérosité glutéale"],a:1,e:"Grand glutéal : fibres SUPERFICIELLES -> tractus ILIO-TIBIAL. Fibres PROFONDES -> crête du grand glutéal."},
  {c:"22",l:"Chap. 2.2",q:"Le moyen glutéal est innervé par :",o:["Nerf glutéal inférieur","Nerf glutéal supérieur","Nerf sciatique","Nerf obturateur"],a:1,e:"Moyen glutéal = nerf glutéal SUPÉRIEUR (comme petit glutéal + TFL). Grand glutéal = nerf glutéal INFÉRIEUR."},
  {c:"22",l:"Chap. 2.2",q:"Le carré fémoral s'insère sur :",o:["Le grand trochanter","La fosse trochantérique","La crête intertrochantérienne","Le petit trochanter"],a:2,e:"Carré fémoral : tubérosité ischiatique -> CRÊTE INTERtrochantérienne. Action : rotation lat. + adduction."},
  {c:"22",l:"Chap. 2.2",q:"Les jumeaux supérieur et inférieur ont des origines différentes. Le jumeau supérieur origine sur :",o:["La tubérosité ischiatique","L'épine ischiatique","Le sacrum","La membrane obturatrice"],a:1,e:"Jumeau SUP : ÉPINE ischiatique. Jumeau INF : TUBÉROSITÉ ischiatique. Les deux -> face int. grand trochanter."},
  // CHAP 2.3
  {c:"23",l:"Chap. 2.3",q:"La patte d'oie superficielle est constituée de :",o:["Sartorius + biceps fémoral + gracile","Semi-tendineux + semi-membraneux + gracile","Sartorius + gracile + semi-tendineux","Sartorius + gracile + poplité"],a:2,e:"Patte d'oie SUPERFICIELLE = Sartorius + Gracile + Semi-tendineux. Insertion sur la face méd. tibia proximal."},
  {c:"23",l:"Chap. 2.3",q:"Le tendon du poplité est :",o:["Extra-capsulaire et extra-synovial","Intra-capsulaire et sort par un trou dans la capsule","Extra-capsulaire et intra-synovial","Intra-capsulaire et intra-synovial"],a:1,e:"Poplité : tendon INTRA-capsulaire qui sort par un TROU dans la partie postérieure de la capsule."},
  {c:"23",l:"Chap. 2.3",q:"Quel mouvement du genou est réalisé par le biceps fémoral uniquement ?",o:["Flexion du genou","Rotation médiale du genou","Rotation latérale du genou","Extension du genou"],a:2,e:"BICEPS FÉMORAL = seul ischio-jambier qui fait la ROTATION LATÉRALE du genou."},
  {c:"23",l:"Chap. 2.3",q:"Le ménisque latéral est en forme de :",o:["C","O (presque circulaire)","V","L"],a:1,e:"Ménisque LATÉRAL = forme de O (presque circulaire). Ménisque MÉDIAL = forme de C (plus grand, moins mobile)."},
  {c:"23",l:"Chap. 2.3",q:"Le ligament poplité ARQUÉ renforce :",o:["La capsule antérieure","La capsule postérieure et limite l'hyperextension","Le LCA","La capsule latérale"],a:1,e:"Lig. poplité ARQUÉ : renforce capsule POST. + limite hyperextension. Lig. poplité OBLIQUE = aussi capsule post."},
  // CHAP 2.5
  {c:"25",l:"Chap. 2.5",q:"Le vaste intermédiaire prend origine sur :",o:["Bord médial ligne âpre fémur","Bord latéral ligne âpre + grand trochanter","Faces antérieure et latérale du corps fémoral","Ligne intertrochantérienne + grand trochanter"],a:2,e:"Vaste intermédiaire : faces ANT. et LAT. du corps fémoral. Vaste lat. = bord lat. ligne âpre. Vaste méd. = bord méd."},
  {c:"25",l:"Chap. 2.5",q:"Le tendon récurrent du semi-membraneux forme :",o:["La patte d'oie superficielle","Le ligament collatéral médial","Le ligament poplité oblique","Le rétinaculum médial patella"],a:2,e:"Semi-membraneux : tendon RÉCURRENT -> ligament POPLITÉ OBLIQUE. Tendon direct -> partie post. condyle méd. tibia."},
  {c:"25",l:"Chap. 2.5",q:"Le gracile réalise sur la jambe :",o:["Extension + rotation latérale","Flexion + rotation médiale","Flexion + rotation latérale","Extension + rotation médiale"],a:1,e:"Gracile : hanche = adduction · jambe = FLEXION + rotation MÉDIALE. Patte d'oie superficielle."},
  {c:"25",l:"Chap. 2.5",q:"L'obturateur externe est innervé par :",o:["Nerf obturateur interne L5–S1","Nerf obturateur L2–L4 (plexus lombaire)","Branches du plexus sacré","Nerf fémoral"],a:1,e:"Obturateur EXTERNE = nerf obturateur L2–L4 (PLEXUS LOMBAIRE). Obturateur INTERNE = L5–S1 (plexus sacré)."},
  {c:"25",l:"Chap. 2.5",q:"Le court adducteur et le long adducteur ont en commun :",o:["Même origine sur branche ischiopubienne","Même innervation par le nerf fémoral","Adduction + flexion + rotation externe cuisse","Insertion sur le tubercule adducteur"],a:2,e:"Court ET long adducteur : adduction + flexion + rotation EXTERNE cuisse. Innervation = nerf obturateur pour les deux."},
  // CHAP 2.6
  {c:"26",l:"Chap. 2.6",q:"Le long extenseur des orteils réalise sur le pied :",o:["Flex. dorsale + adduction + supination","Flex. dorsale + abduction + pronation","Flex. plantaire + abduction","Extension + inversion"],a:1,e:"Long ext. orteils : extension orteils + flex. dorsale + ABDUCTION + PRONATION. (tibial ant. = adduction + supination)."},
  {c:"26",l:"Chap. 2.6",q:"Le 3e fibulaire est :",o:["Toujours présent et bien développé","Muscle inconstant souvent fusionné avec le long ext. orteils","Le même muscle que le court fibulaire","Un muscle de la loge postérieure"],a:1,e:"3e fibulaire = INCONSTANT, souvent fusionné avec le long ext. orteils. Face int. fibula -> base 5e métatarsien."},
  {c:"26",l:"Chap. 2.6",q:"Le plantaire prend origine sur :",o:["Condyle méd. fémur","Face post. tibia","Condyle lat. fémur (profond/gastrocnémien)","Tête fibulaire"],a:2,e:"Plantaire : condyle LAT. fémur (profond par rapport au gastrocnémien) -> bord méd. tendon d'Achille."},
  {c:"26",l:"Chap. 2.6",q:"L'articulation talocalcanéo-naviculaire (Chopart médiale) a comme surface articulaire :",o:["Uniquement tête du talus + naviculaire","Tête du talus + naviculaire + face ant. calcanéum + lig. Spring","Talus + cuboïde + naviculaire","Calcanéum + cuboïde uniquement"],a:1,e:"Talocalcanéo-naviculaire : tête du talus + face post. naviculaire + face ant. sup. calcanéum + lig. de SPRING."},
  {c:"26",l:"Chap. 2.6",q:"Le long fléchisseur de l'hallux prend origine sur :",o:["Face post. tibia 1/3 moyen","Membrane interosseuse","Fibula 1/2 distal","Condyle lat. tibia + fibula"],a:2,e:"Long fléchisseur hallux : FIBULA (1/2 distal) -> base phalange distale hallux. Flex. hallux + inversion."},
  // CHAP 2.7
  {c:"27",l:"Chap. 2.7",q:"Le court fléchisseur de l'hallux est innervé par :",o:["Nerf plantaire latéral uniquement","Nerf fibulaire profond","Nerfs plantaires médial ET latéral","Nerf plantaire médial uniquement"],a:2,e:"Court fléch. hallux = nerfs plantaires MÉDIAL ET LATÉRAL (innervation mixte). S'insère via les sésamoïdes."},
  {c:"27",l:"Chap. 2.7",q:"L'aponévrose plantaire s'attache postérieurement sur :",o:["Le naviculaire","Le talus","Le calcanéum","Le 1er métatarsien"],a:2,e:"Aponévrose plantaire : s'attache au CALCANÉUM en postérieur -> se divise en 5 fascicules vers les orteils."},
  {c:"27",l:"Chap. 2.7",q:"Le court extenseur des orteils (pédieux) est divisé en :",o:["2 fascicules","3 fascicules","4 fascicules","5 fascicules"],a:1,e:"Court ext. orteils = 3 FASCICULES -> tendons du long ext. orteils (2e, 3e, 4e orteils). Nerf fibulaire profond."},
  {c:"27",l:"Chap. 2.7",q:"Le fléchisseur du 5e orteil prend origine sur :",o:["Face inférieure calcanéum","Tubercule 5e métatarsien","Base 5e métatarsien + long lig. plantaire","Moitié distale 5e métatarsien"],a:2,e:"Fléchisseur 5e : BASE 5e métatarsien + long ligament plantaire -> base 1ère phalange 5e orteil."},
  {c:"27",l:"Chap. 2.7",q:"L'abducteur du 5e orteil prend origine sur :",o:["Base 5e métatarsien","Tubercule 5e métatarsien","Face inférieure calcanéum","Long ligament plantaire"],a:2,e:"Abducteur 5e : face INF. calcanéum -> face lat. 1ère phalange 5e orteil. Action : flexion + ABDUCTION."},
  // CHAP 2.8
  {c:"28",l:"Chap. 2.8",q:"Le nerf obturateur innerve en moteur :",o:["Quadriceps + sartorius + pectiné","Gracile + adducteurs + obturateur ext.","Ischio-jambiers + grand adducteur","Grand glutéal + moyen glutéal"],a:1,e:"Nerf obturateur : gracile + long add. + court add. + grand add. (faisceau add.) + obturateur ext. + sensitif face int. cuisse."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf fibulaire superficiel innerve en moteur :",o:["Zone antérieure jambe","Long + court fibulaire","Tibial antérieur uniquement","Interosseux du pied"],a:1,e:"Fibulaire SUPERFICIEL : long fibulaire + court fibulaire. Sensitif : face dorsale pied."},
  {c:"28",l:"Chap. 2.8",q:"Le plexus sacré est formé par :",o:["Branches ant. L1–L4","Tronc lombo-sacré + branches ant. S1–S3","Branches ant. S1–S5","Branches ant. L5–S4"],a:1,e:"Plexus sacré = TRONC LOMBO-SACRÉ (L4–L5) + branches ant. S1–S3."},
  {c:"28",l:"Chap. 2.8",q:"Dans la jambe, la zone antérieure est innervée par :",o:["Nerf tibial","Nerf fibulaire superficiel","Nerf fibulaire profond","Nerf saphène"],a:2,e:"Zone ANT. jambe = nerf FIBULAIRE PROFOND (tibial ant. + long ext. orteils + long ext. hallux + 3e fibulaire)."},
  {c:"28",l:"Chap. 2.8",q:"Le nerf fémoral est la branche la plus importante du plexus lombaire ?",o:["Vrai","Faux"],a:0,e:"VRAI. Le nerf FÉMORAL est la branche la PLUS IMPORTANTE du plexus lombaire (L2–L4)."}
];

var ALL_Q = MAIN_Q.concat(EXTRA_Q).concat(EXTRA_Q2);

window.ANAT_BANK = ALL_Q.map(function(item) {
  return {
    ch: item.l,
    label: 'QCM anatomie',
    type: 'direct',
    q: item.q,
    opts: item.o,
    a: item.a,
    e: item.e
  };
});
