// Banque Anatomie convertie pour le moteur sandbox.js
// Format source: { c, l, q, o, a, e }

var MAIN_Q = [
 // ══════════════════════════════════════════════════════════════
// NEUROPLASTICITÉ (20 questions)
// ══════════════════════════════════════════════════════════════
{ch:"neuroplasticite",q:"Quelle est la définition la plus complète de la neuroplasticité selon Álvaro Pascual-Leone (2010) ?",opts:["La capacité du SNC à régénérer les axones sectionnés après une lésion traumatique périphérique","La propriété intrinsèque du cerveau à se réorganiser et s'adapter aux exigences fonctionnelles et environnementales tout au long de la vie","Le processus exclusif de synaptogenèse observé uniquement pendant les périodes critiques du développement"],ans:1,fb:"Pascual-Leone définit la neuroplasticité comme une propriété intrinsèque permettant au SNC de contourner les limites de son génome pour s'adapter à l'environnement et à l'expérience."},
 
{ch:"neuroplasticite",q:"Selon le principe 'Use it or lose it', que se passe-t-il sur le plan cortical lors d'une non-utilisation prolongée d'un membre ?",opts:["Une hypertrophie compensatoire des zones adjacentes","Une perte de la représentation corticale du territoire non utilisé","Une augmentation réflexe de l'excitabilité spinale pour compenser"],ans:1,fb:"La désutilisation fonctionnelle entraîne une réduction de la représentation corticale du territoire concerné. C'est la base du concept d'apprentissage au désusage post-AVC."},
 
{ch:"neuroplasticite",q:"Le phénomène de diaschisis correspond à :",opts:["Une régénération axonale après lésion du nerf périphérique","Des modifications fonctionnelles dans des zones cérébrales éloignées de la lésion, dues à la déconnexion des réseaux neuronaux","Une réaction inflammatoire locale autour de la zone lésée"],ans:1,fb:"Le diaschisis (Carrera & Tononi, 2014) : la lésion interrompt des connexions vers d'autres zones qui cessent de fonctionner normalement, même si elles ne sont pas directement atteintes."},
 
{ch:"neuroplasticite",q:"La plasticité cross-modale est considérée comme maladaptative chez le patient hémiparétique car :",opts:["Elle provoque une hyperexcitabilité du cortex ipsilésionnel","Elle permet au cortex visuel de traiter des informations somatosensorielles, limitant la récupération optimale","Elle génère une synaptogenèse excessive dans les zones non lésées"],ans:1,fb:"La plasticité cross-modale est adaptative chez l'aveugle mais maladaptative post-AVC : la prise en charge du territoire somatosensoriel par le visuel limite la réorganisation optimale de la récupération motrice."},
 
{ch:"neuroplasticite",q:"Parmi ces facteurs, lequel est MODIFIABLE pour optimiser la neuroplasticité ?",opts:["L'âge au moment de la lésion","La localisation exacte de la lésion cérébrale","La qualité du sommeil et du repos"],ans:2,fb:"Sommeil, alimentation, motivation, médicaments et type/timing du traitement sont modifiables. L'âge, la localisation et l'extension de la lésion sont des facteurs peu ou pas modifiables."},
 
{ch:"neuroplasticite",q:"La surutilisation du membre sain après AVC (Taub et al., 2006) peut entraîner :",opts:["Une récupération accélérée du membre affecté par effet de transfert bilatéral","Une inhibition de la réorganisation corticale nécessaire à la récupération du côté affecté","Une spasticité accrue du membre sain par surmenage neuromoteur"],ans:1,fb:"L'excès d'utilisation du membre sain réduit le besoin d'utiliser le côté atteint, limitant la réorganisation corticale adaptative et perpétuant le phénomène d'apprentissage au désusage."},
 
{ch:"neuroplasticite",q:"Quelle est la différence entre plasticité adaptative et plasticité maladaptative ?",opts:["La plasticité adaptative survient seulement en phase aiguë","La plasticité adaptative favorise la récupération fonctionnelle ; la maladaptative génère des compensations inefficaces entravant la récupération","La plasticité maladaptative est toujours irréversible"],ans:1,fb:"Les deux formes coexistent. La plasticité maladaptative (ex. spasticité stéréotypée, réactions associées) peut se développer sans rééducation ou avec une rééducation inadaptée (Nudo, 2013)."},
 
{ch:"neuroplasticite",q:"Le principe de spécificité en neuroplasticité signifie que :",opts:["Plus les répétitions sont nombreuses, plus les changements neuronaux sont importants, quelle que soit la tâche","L'entraînement doit reproduire le comportement cible souhaité pour induire des changements spécifiques","Le cerveau ne peut se réorganiser que sur des zones adjacentes à la lésion"],ans:1,fb:"La spécificité (Kleim & Jones, 2008) : les changements neuronaux induits correspondent précisément à la tâche pratiquée. Un entraînement de la marche ne renforce pas la préhension."},
 
{ch:"neuroplasticite",q:"La protéine GAP-43 (Growth Associated Protein) joue un rôle dans la neuroplasticité post-lésionnelle en :",opts:["Inhibant la synaptogenèse pour protéger les zones de pénombre","Facilitant la synaptogenèse après libération par les cellules endommagées","Accélérant la démyélinisation des fibres lésées"],ans:1,fb:"Après lésion, les cellules endommagées libèrent des protéines GAP-43 qui facilitent la synaptogenèse et participent à la mise en place des mécanismes de neuroplasticité post-lésionnelle."},
 
{ch:"neuroplasticite",q:"La réorganisation corticale controlatérale après AVC peut être :",opts:["Toujours aussi efficace que la réorganisation ipsilésionnelle pour le transfert de fonctions motrices spécifiques","Moins efficace pour transférer les fonctions motrices spécifiques, notamment la spécialisation fonctionnelle","Uniquement bénéfique et jamais source de plasticité maladaptative"],ans:1,fb:"La réorganisation controlatérale (hémisphère sain) peut compenser certaines fonctions mais présente des limites pour les fonctions très spécialisées. De plus, l'activation excessive de l'hémisphère sain peut inhiber la récupération ipsilésionnelle."},
 
{ch:"neuroplasticite",q:"Selon Ferriero (2024), comment doit être conçue une intervention de rééducation en termes de dosage ?",opts:["Maximale en intensité dès le début, quel que soit le profil du patient","Ajustée de façon individualisée, avec un dosage optimal, une fréquence adéquate et une durée suffisante","Identique pour tous les patients post-AVC selon les protocoles standardisés"],ans:1,fb:"Ferriero compare la rééducation à un médicament : elle doit être dosée individuellement. Un excès peut aussi être néfaste (fatigue, surcharge, plasticité inadaptée)."},
 
{ch:"neuroplasticite",q:"La LTP (Long-Term Potentiation) est un mécanisme cellulaire expliquant :",opts:["La diminution durable de l'efficacité synaptique après stimulation répétée à basse fréquence","L'augmentation durable de l'efficacité synaptique, base de l'apprentissage et de la mémoire","La destruction des synapses inutilisées pendant les périodes critiques du développement"],ans:1,fb:"La LTP est une augmentation durable de la transmission synaptique induite par une stimulation répétée à haute fréquence. C'est l'un des mécanismes fondamentaux de l'apprentissage moteur et de la neuroplasticité."},
 
{ch:"neuroplasticite",q:"Le concept de 'thérapies adaptatives' en neuroréhabilitation (Boyd) consiste à :",opts:["Appliquer le même protocole standard à tous les patients pour garantir la reproductibilité","Ajuster les variables thérapeutiques (temps, intensité, difficulté) au moment neurologique et au profil individuel du patient","Privilégier systématiquement les thérapies passives pour éviter la fatigue neuronale"],ans:1,fb:"Les thérapies adaptatives reconnaissent que la neuroplasticité n'est pas homogène et dépend du profil individuel, du stade lésionnel et des paramètres de stimulation. Il n'existe pas de protocole universel optimal."},
 
{ch:"neuroplasticite",q:"Quel est le rôle de la névroglie dans les mécanismes de neuroplasticité ?",opts:["La névroglie est une structure passive sans rôle actif dans la plasticité neuronale","Elle module l'activité synaptique, participe à la synaptogenèse et joue un rôle clé dans la réponse à la lésion","Elle inhibe exclusivement la synaptogenèse pour prévenir les connexions aberrantes"],ans:1,fb:"La névroglie (astrocytes, oligodendrocytes, microglie) est active dans la neuroplasticité : régulation synaptique, synaptogenèse, élimination des débris post-lésionnels et formation de la cicatrice gliale."},
 
{ch:"neuroplasticite",q:"Le maintien des acquis thérapeutiques (S. Cramer) dépend de :",opts:["La phase de la lésion uniquement : les acquis de la phase aiguë sont toujours permanents","La continuité d'une exposition thérapeutique, car l'entraînement des capacités peut s'améliorer mais les acquis dépendent souvent d'une pratique continue","L'âge du patient : les patients jeunes maintiennent toujours leurs acquis sans pratique supplémentaire"],ans:1,fb:"S. Cramer souligne que dans de nombreux cas, le maintien des acquis nécessite une exposition thérapeutique continue. Sans pratique, les représentations corticales peuvent régresser."},
 
{ch:"neuroplasticite",q:"La neurogenèse chez l'adulte a été prouvée principalement dans :",opts:["Le cortex moteur primaire et le cervelet","L'hippocampe et le bulbe olfactif","Le cortex préfrontal et le thalamus"],ans:1,fb:"La neurogenèse adulte est principalement documentée dans l'hippocampe (mémoire spatiale, apprentissage) et le bulbe olfactif, à partir de cellules souches neurales épendymaires."},
 
{ch:"neuroplasticite",q:"Les 'réactions associées' chez un patient hémiparétique sont un exemple de :",opts:["Plasticité adaptative, car elles maintiennent une activité motrice du côté affecté","Plasticité maladaptative, car elles renforcent des synergies anormales non fonctionnelles","Mécanismes réflexes spinaux normaux sans lien avec la plasticité cérébrale"],ans:1,fb:"Les réactions associées (mouvements involontaires du membre affecté lors d'efforts) représentent une plasticité maladaptative : elles renforcent des schémas stéréotypés globaux non sélectifs."},
 
{ch:"neuroplasticite",q:"Selon les principes de neuroplasticité, le moment idéal pour débuter la rééducation est :",opts:["6 mois après la lésion, quand la neuroplasticité spontanée est maximale","Le plus tôt possible dès que l'état clinique le permet, la phase précoce offrant le plus fort potentiel plastique","1 mois après la lésion, une fois la phase de choc neural complètement résolue"],ans:1,fb:"Le principe 'durée' (Kleim & Jones) : commencer tôt favorise de meilleurs résultats. Cependant, un potentiel de plasticité persiste même en phase chronique, même si moins important."},
 
{ch:"neuroplasticite",q:"Les mouvements compensatoires précoces après AVC (Takeuchi & Izumi, 2012) peuvent entraîner à long terme :",opts:["Une récupération complète de la fonction grâce à l'apprentissage par substitution","Un désapprentissage, une réduction de l'amplitude, des désalignements posturaux et des douleurs chroniques","Une augmentation de la force musculaire du côté affecté par stimulation indirecte"],ans:1,fb:"Les compensations précoces aident à court terme mais risquent de créer des schémas stéréotypés, un désapprentissage du côté affecté, des douleurs et des déformations posturales à long terme."},
 
{ch:"neuroplasticite",q:"La plasticité structurelle se distingue de la plasticité fonctionnelle car :",opts:["La plasticité structurelle est rapide et transitoire ; la fonctionnelle est lente et permanente","La plasticité structurelle implique des changements anatomiques (synapses, myéline, dendrites) ; la fonctionnelle modifie l'efficacité des réseaux existants","La plasticité fonctionnelle n'existe que pendant l'enfance"],ans:1,fb:"Plasticité fonctionnelle : modifications de l'efficacité des réseaux existants (à court terme). Plasticité structurelle : changements anatomiques réels — synaptogenèse, myélinisation, remodelage dendritique (plus durable)."},
 
// ══════════════════════════════════════════════════════════════
// ÉVALUATION (20 questions)
// ══════════════════════════════════════════════════════════════
{ch:"evaluation",q:"Le Berg Balance Scale (BBS) est coté sur :",opts:["28 points avec 14 items","56 points avec 14 items cotés 0 à 4","100 points avec 20 items"],ans:1,fb:"Le BBS : 14 items × 4 points = 56 points au maximum. Risque faible ≥ 41 ; risque moyen 21-40 ; risque élevé 0-20 (Berg et al., 1992)."},
 
{ch:"evaluation",q:"Le test du contrôle du tronc (TCT) prédit :",opts:["La récupération des fonctions cognitives à 6 mois","La capacité de récupération de la marche à 18 semaines si le score est ≥ 50 à 6 semaines post-AVC","Le risque de récidive d'AVC dans l'année suivante"],ans:1,fb:"TCT coté 0-100. Un score ≥ 50 à 6 semaines post-AVC est un indicateur prédictif de la récupération de la marche fonctionnelle à 18 semaines."},
 
{ch:"evaluation",q:"Quelle est la principale différence entre le Barthel et la FIM pour l'évaluation des AVQ ?",opts:["Le Barthel est plus sensible aux changements subtils grâce à ses 7 niveaux par item","La FIM (18 items, 7 niveaux) est plus sensible aux changements fins que le Barthel (10 items, tranches larges)","Les deux outils sont équivalents en termes de sensibilité au changement"],ans:1,fb:"Le FIM détecte un patient passant de 'assistance maximale' à 'assistance minimale' (2→4) là où le Barthel resterait à 5 dans les deux cas. Sa graduation en 7 niveaux le rend plus sensible."},
 
{ch:"evaluation",q:"L'effet plafond dans une échelle d'évaluation signifie que :",opts:["Les patients les plus légers atteignent le score maximal, rendant les améliorations ultérieures indétectables","Les patients les plus sévères restent au score minimal, empêchant la détection des aggravations","L'échelle est trop longue et fatigante pour être administrée en pratique clinique"],ans:0,fb:"L'effet plafond (ceiling effect) : les patients peu déficitaires atteignent le maximum, donc toute amélioration passe inaperçue. Ex. : le BBS pour des patients légers → intérêt du Mini-BESTest."},
 
{ch:"evaluation",q:"Le TUG (Timed Up and Go) mesure :",opts:["La vitesse de marche sur une distance fixe de 10 mètres","Le temps nécessaire pour se lever d'une chaise, marcher 3 mètres, faire demi-tour et se rasseoir","La distance maximale parcourue en 6 minutes"],ans:1,fb:"Le TUG est un test simple évaluant la mobilité fonctionnelle et le risque de chute. Il est utilisé chez les personnes âgées et neurologiques, et peut être couplé à une double tâche."},
 
{ch:"evaluation",q:"La Wisconsin Gait Scale (WGS) est spécifiquement conçue pour :",opts:["Évaluer l'équilibre statique chez les patients parkinsoniens","Évaluer qualitativement le schéma de marche post-AVC en analysant l'asymétrie et les mouvements segmentaires","Mesurer l'endurance à la marche chez les patients atteints de sclérose en plaques"],ans:1,fb:"La WGS : 14 éléments évaluant chaque phase de la marche (qualitative), spécifiquement développée pour les patients post-AVC avec focus sur l'asymétrie et les patterns de mouvement."},
 
{ch:"evaluation",q:"La validité conceptuelle (construct validity) d'une échelle est démontrée quand :",opts:["L'échelle mesure systématiquement les mêmes résultats quel que soit l'évaluateur","Les résultats de l'échelle sont positivement corrélés avec ceux d'autres outils mesurant des aspects connexes","L'échelle contient des items représentatifs de toutes les dimensions du concept mesuré"],ans:1,fb:"La validité conceptuelle (convergente) : si l'échelle est valide, elle doit être corrélée positivement avec d'autres échelles mesurant des concepts similaires (ex. BBS et Mini-BESTest)."},
 
{ch:"evaluation",q:"La FAC (Functional Ambulation Categories) évalue :",opts:["La qualité du schéma de marche par analyse observationnelle segmentaire","Le niveau de dépendance à l'aide humaine ou technique pour la marche","La vitesse et l'endurance de marche sur terrain plat et escaliers"],ans:1,fb:"La FAC est une échelle ordinale classant les patients selon leur niveau d'autonomie à la marche (0 = incapable de marcher à 5 = marche indépendante sur tous terrains)."},
 
{ch:"evaluation",q:"Le changement minimal détectable (MCD) se distingue de la différence minimale cliniquement importante (DMCI) car :",opts:["Le MCD est toujours supérieur à la DMCI","Le MCD représente le seuil au-delà duquel un changement est réel et non dû à l'erreur de mesure ; la DMCI représente le seuil de signification fonctionnelle pour le patient","Le MCD est subjectif et basé sur le ressenti du patient"],ans:1,fb:"Un changement supérieur au MCD est réel (pas une erreur de mesure). Pour qu'il soit cliniquement significatif pour le patient, il doit atteindre la DMCI. Ex. BBS : MCD = 6 pts, DMCI = 7 pts."},
 
{ch:"evaluation",q:"La PASS (Postural Assessment Scale for Stroke) présente un avantage sur le BBS car :",opts:["Elle comporte plus d'items et une cotation plus fine","Elle commence en décubitus dorsal, évitant l'effet plancher du BBS pour les patients très atteints","Elle évalue spécifiquement les transferts et la locomotion fonctionnelle"],ans:1,fb:"La PASS débute en décubitus et évalue des changements de posture très précoces (décubitus→latéral→assis). Le BBS commence en position assise, ce qui génère un effet plancher pour les patients très déficitaires."},
 
{ch:"evaluation",q:"Pour évaluer la récupération motrice du membre supérieur post-AVC, l'échelle de référence est :",opts:["L'Action Research Arm Test (ARAT) uniquement","La Fugl-Meyer Assessment (FMA) — sous-échelle membres supérieurs","Le Motricity Index (MI)"],ans:1,fb:"La FMA est l'échelle de référence pour la récupération motrice post-AVC (synergies, mouvement sélectif, coordination). L'ARAT évalue la fonction de préhension ; le MI évalue la force dans les mouvements clés."},
 
{ch:"evaluation",q:"Le Box and Block Test (BBT) mesure :",opts:["La coordination bimanuelle et la dextérité fine des doigts avec des chevilles","La dextérité manuelle globale : nombre de cubes transférés d'un compartiment à l'autre en 60 secondes","La force de préhension palmaire et la résistance à la fatigue"],ans:1,fb:"Le BBT mesure la dextérité manuelle globale (gross manual dexterity) : le patient transfère le maximum de cubes d'un compartiment à l'autre en 60 secondes."},
 
{ch:"evaluation",q:"L'EDSS (Expanded Disability Status Scale) est utilisé spécifiquement dans :",opts:["La maladie de Parkinson pour évaluer le stade de progression","La sclérose en plaques pour évaluer le degré global d'incapacité neurologique","L'AVC pour évaluer la sévérité initiale"],ans:1,fb:"L'EDSS évalue le handicap global dans la sclérose en plaques. Pour Parkinson : UPDRS et Hoehn & Yahr. Pour l'AVC : NIHSS (sévérité initiale) et Fugl-Meyer (récupération motrice)."},
 
{ch:"evaluation",q:"Le MoCA (Montreal Cognitive Assessment) est un outil de :",opts:["Rééducation cognitive intensive pour les patients post-TCC","Dépistage du déclin cognitif léger et des troubles neurocognitifs acquis","Diagnostic différentiel entre Parkinson et démence à corps de Lewy"],ans:1,fb:"Le MoCA (Nasreddine et al., 2005) est un test de dépistage rapide du déclin cognitif léger. Il explore mémoire, attention, fonctions exécutives, langage, visuo-spatial et orientation."},
 
{ch:"evaluation",q:"Le site SRALab (sralab.org/rehabilitation-measures) est utile pour :",opts:["Télécharger des protocoles de rééducation validés pour chaque pathologie","Vérifier si une échelle est validée pour une population spécifique et ses propriétés psychométriques","Calculer automatiquement les scores des principales échelles neurologiques"],ans:1,fb:"Le Rehabilitation Measures Database (SRALab) recense les échelles d'évaluation clinique, leurs propriétés psychométriques, les populations pour lesquelles elles sont validées, et les valeurs normatives."},
 
{ch:"evaluation",q:"Pour évaluer la qualité de vie liée à la maladie de Parkinson, on utilise :",opts:["MSIS-29 (Multiple Sclerosis Impact Scale)","PDQ-39 (Parkinson's Disease Questionnaire)","ALSFRS-R (ALS Functional Rating Scale-Revised)"],ans:1,fb:"PDQ-39 : qualité de vie spécifique à Parkinson. MSIS-29 : qualité de vie dans la SEP. ALSFRS-R : capacité fonctionnelle dans la SLA. SF-36 : qualité de vie générique (toutes pathologies)."},
 
{ch:"evaluation",q:"La fiabilité inter-observateur d'une échelle évalue :",opts:["La cohérence des résultats lorsque le même évaluateur répète la mesure à deux moments différents","La concordance des scores obtenus par deux évaluateurs différents appliquant la même échelle au même moment","La capacité de l'échelle à détecter des changements cliniquement significatifs"],ans:1,fb:"Fiabilité inter-observateur : concordance entre deux évaluateurs différents (ex. kappa de Cohen). Fiabilité intra-observateur : concordance du même évaluateur à des moments différents."},
 
{ch:"evaluation",q:"La Lawton & Brody évalue :",opts:["Les activités basiques (alimentation, hygiène, transferts)","Les activités instrumentales de la vie quotidienne (téléphone, courses, repas, médicaments, finances)","La qualité de vie et la participation sociale chez les personnes âgées"],ans:1,fb:"La Lawton & Brody évalue les AIVQ instrumentales : téléphone, achats, repas, lessive, maison, transport, médicaments, finances. Score max = 8 (fonctionnalité maximale)."},
 
{ch:"evaluation",q:"Dans un essai clinique, utiliser le NIHSS comme outcome primaire pour évaluer la récupération post-AVC à 6 mois présente la limite que :",opts:["Le NIHSS n'est pas validé pour la phase chronique","Le NIHSS mesure la sévérité neurologique initiale mais n'est pas la mesure la plus sensible de la récupération fonctionnelle à distance","Le NIHSS ne peut pas être utilisé par des physiothérapeutes"],ans:1,fb:"Le NIHSS est conçu pour évaluer la sévérité neurologique aiguë. Pour la récupération fonctionnelle à distance, des mesures comme le Fugl-Meyer, l'indice de Barthel ou la Stroke Impact Scale sont plus appropriées."},
 
{ch:"evaluation",q:"Lors du calcul d'un score FIM, un score de 4 à l'item alimentation signifie :",opts:["Indépendance totale sans dispositif","Assistance minimale : le patient réalise ≥ 75% de l'effort","Assistance modérée : le patient réalise 50 à 74% de l'effort"],ans:1,fb:"FIM alimentation : 7 = indépendant total, 6 = indépendant modifié (dispositif), 5 = supervision, 4 = assistance minimale (patient ≥75%), 3 = assistance modérée (50-74%), 2 = assistance max (<25-49%), 1 = dépendance totale."},
 
// ══════════════════════════════════════════════════════════════
// OUTILS THÉRAPEUTIQUES (22 questions)
// ══════════════════════════════════════════════════════════════
{ch:"outils",q:"La thérapie par contrainte induite (CIMT) repose sur le principe que :",opts:["La restriction du membre sain permet d'éviter la fatigue du membre affecté","Restreindre le membre sain force le cerveau à réorganiser le contrôle du membre affecté par neuroplasticité","Le membre affecté récupère spontanément si le membre sain est immobilisé suffisamment longtemps"],ans:1,fb:"La CIMT (Constraint-Induced Movement Therapy) : la restriction du membre sain (attelle, gant) force l'utilisation du membre affecté, induisant une réorganisation corticale et contrant l'apprentissage au désusage."},
 
{ch:"outils",q:"Le protocole optimal de CIMT selon Yang et al. (2023) implique :",opts:["24 heures de restriction par jour pendant 2 semaines","6 heures d'entraînement par semaine avec 6 heures de restriction par jour","12 heures d'entraînement par jour pendant 10 jours consécutifs"],ans:1,fb:"Un protocole efficace : 6 heures d'entraînement/semaine avec 6 heures de restriction/jour, associé à des tâches fonctionnelles répétitives. Le moment de la thérapie par rapport à l'AVC influence aussi l'efficacité."},
 
{ch:"outils",q:"Le Repetitive Task Training (RTT) a montré une amélioration significative sur :",opts:["Principalement la force musculaire et la spasticité","La distance de marche (environ 35 m de plus en 6 minutes), la déambulation fonctionnelle et les AVQ","Exclusivement la fonction du membre supérieur sans effet sur la marche"],ans:1,fb:"French et al. (2016, Cochrane) : le RTT améliore la distance de marche (~35 m en 6MWT), l'indice de Barthel et le 10MWT. Les effets se maintiennent jusqu'à 6 mois mais pas entre 6 mois et 1 an."},
 
{ch:"outils",q:"Les instructions axées sur les objectifs (goal-oriented instructions) dans le RTT augmentent l'intensité de pratique de :",opts:["10 à 25%","62 à 128%","200 à 300%"],ans:1,fb:"Hillig et al. (2019) : les instructions axées sur les objectifs (vitesse, amélioration personnelle) augmentent de 62 à 128% le nombre de répétitions vs instructions non spécifiques. Les plus efficaces encouragent la vitesse."},
 
{ch:"outils",q:"La tDCS cathodique sur une zone corticale entraîne :",opts:["Une dépolarisation membranaire augmentant l'excitabilité corticale","Une hyperpolarisation membranaire diminuant l'excitabilité et la probabilité de potentiels d'action","Un effet identique à l'anode mais de plus courte durée"],ans:1,fb:"La cathode provoque une hyperpolarisation partielle du potentiel membranaire, éloignant les neurones du seuil de déclenchement → réduction de l'excitabilité. Utilisée pour inhiber les zones hyperactives."},
 
{ch:"outils",q:"La tDCS 'en ligne' (online) vs 'hors ligne' (offline) diffère car :",opts:["La tDCS en ligne est plus sûre car elle ne stimule pas pendant l'activité cérébrale","La tDCS en ligne est administrée pendant la tâche, générant des effets plus spécifiques et état-dépendants ; la hors ligne est appliquée avant","La tDCS hors ligne est plus efficace pour induire des mécanismes similaires à la LTP"],ans:1,fb:"tDCS en ligne : application simultanée à la tâche → interaction directe avec les processus neurophysiologiques actifs → effets plus spécifiques et dépendants de l'état cortical du moment."},
 
{ch:"outils",q:"La rTMS à basse fréquence (1 Hz) est utilisée après un AVC pour :",opts:["Exciter le cortex moteur ipsilésionnel pour favoriser la récupération","Inhiber le cortex moteur controlatéral sain, dont l'hyperactivité peut inhiber l'hémisphère lésé","Activer le cortex préfrontal dorsolatéral gauche dans le traitement de la dépression post-AVC"],ans:1,fb:"Après AVC, le déséquilibre interhémisphérique crée une inhibition accrue de l'hémisphère lésé par le sain. La rTMS 1 Hz inhibe l'hémisphère sain, réduisant cette inhibition croisée et favorisant la récupération."},
 
{ch:"outils",q:"La NMES active les fibres musculaires dans quel ordre, contrairement à la contraction volontaire ?",opts:["Elle recrute d'abord les fibres lentes de type I, comme la contraction volontaire","Elle recrute d'abord les fibres rapides de type II (recrutement inverse), contrairement à la contraction volontaire","Elle recrute simultanément tous les types de fibres sans distinction de seuil"],ans:1,fb:"La NMES réalise un recrutement inverse (rapide → lente) car elle active directement les fibres motrices via le courant électrique, indépendamment du seuil de recrutement physiologique."},
 
{ch:"outils",q:"La FES contrôlée par EMG (electromyographie) permet :",opts:["D'appliquer la stimulation à haute intensité sans risque de contraction douloureuse","De déclencher la stimulation électrique en réponse à une tentative volontaire du patient, couplant intention et mouvement","De remplacer l'intention motrice par une commande artificielle externe"],ans:1,fb:"La FES-EMG détecte l'intention motrice résiduelle via le signal EMG et déclenche la stimulation en synchronisation, renforçant le couplage intention-action et favorisant la plasticité corticomotrice."},
 
{ch:"outils",q:"Le concept Bobath actuel (Vaughan-Graham et al., 2020) intègre :",opts:["Uniquement les techniques de facilitation manuelle développées par Berta Bobath dans les années 1940","Les sciences contemporaines du mouvement, les neurosciences et une approche individualisée axée sur le problème clinique","Des protocoles d'exercices standardisés applicables uniformément à tous les patients neurologiques"],ans:1,fb:"La définition révisée du concept Bobath (2020) : approche inclusive et individualisée s'appuyant sur les neurosciences contemporaines, la facilitation sensorielle et l'auto-organisation du mouvement."},
 
{ch:"outils",q:"Dans l'exercice thérapeutique cognitif de Perfetti, les exercices de 1er degré sont :",opts:["Des mouvements actifs autonomes permettant l'automatisation","Des mouvements passifs avec forte composante attentionnelle, agissant sur l'adaptation du tonus et les déficits sensoriels","Des mouvements assistés agissant sur le contrôle des contractions musculaires"],ans:1,fb:"1er degré : mouvement passif du thérapeute, yeux fermés, avec forte composante attentionnelle (hypothèse perceptive + vérification). 2e degré : assisté. 3e degré : actif autonome avec automatisation."},
 
{ch:"outils",q:"La thérapie Vojta est fondée sur l'activation de :",opts:["Des schémas moteurs volontaires appris par la répétition explicite","Des schémas moteurs globaux réflexes (locomotion réflexe) déclenchés par stimuli sur zones précises depuis positions définies","Des réflexes primitifs archaïques normalement inhibés chez l'adulte sain"],ans:1,fb:"Vojta : depuis des positions définies + stimulations sur zones précises → activation d'un schéma de locomotion réflexe (contrôle postural automatique + ajustements + mouvement phasique coordonné)."},
 
{ch:"outils",q:"L'Armeo Spring est un dispositif robotique de type :",opts:["Effecteur final pour la rééducation des membres supérieurs distaux","Exosquelette unilatéral avec 6 degrés de liberté permettant la suspension et l'assistance du MS dans des tâches en RV","Orthèse robotisée portable contrôlée par EMG pour usage à domicile"],ans:1,fb:"L'Armeo Spring est un exosquelette unilatéral (6 GDL) qui suspend le membre supérieur et l'assiste/résiste lors de tâches fonctionnelles en réalité virtuelle sur bureau (épaule, coude, poignet, préhension)."},
 
{ch:"outils",q:"Le concept Halliwick en thérapie aquatique suit un programme en :",opts:["6 étapes progressives de flottabilité et propulsion","10 points progressifs allant de l'adaptation mentale à la propulsion simple","4 phases correspondant aux 4 propriétés physiques de l'eau"],ans:1,fb:"Halliwick : programme en 10 points (adaptation mentale, relâchement, rotations transversale/sagittale/longitudinale/combinée, poussée vers le haut, équilibre statique, turbulences, propulsion)."},
 
{ch:"outils",q:"La réalité virtuelle totalement immersive (casque VR) a montré les meilleures améliorations sur :",opts:["La dextérité fine et la préhension digitale","La motricité globale du membre supérieur, avec de meilleurs résultats que les approches non immersives pour ce paramètre","La réduction de la spasticité et du tonus musculaire"],ans:1,fb:"Soleimani et al. (2024) : la RV totalement immersive montre les meilleures améliorations en motricité globale (FMA), tandis que les approches non immersives améliorent davantage la dextérité fine."},
 
{ch:"outils",q:"La thérapie par observation d'actions (AOT) active principalement :",opts:["Le cortex visuel primaire par stimulation optique directe","Le système des neurones miroirs, favorisant la récupération motrice par observation des mouvements","Le cervelet pour la correction des erreurs motrices pendant l'observation"],ans:1,fb:"L'AOT active le système des neurones miroirs (MNS) : observer une action active les mêmes circuits que l'exécuter. Cela facilite le réapprentissage moteur sans nécessiter de mouvement actif."},
 
{ch:"outils",q:"Le Lokomat produit combien de pas par séance de 30 minutes en comparaison avec la thérapie conventionnelle ?",opts:["200 à 300 pas vs 50 à 100 en thérapie conventionnelle","Plus de 1000 pas vs 50 à 100 pas en thérapie conventionnelle","500 à 600 pas, similaire à la thérapie conventionnelle"],ans:1,fb:"Le Lokomat permet >1000 pas en 30 minutes, contre seulement 50-100 pas en thérapie conventionnelle. Cette différence illustre l'intérêt des dispositifs robotiques pour augmenter le volume de pratique."},
 
{ch:"outils",q:"La stimulation basale (Basal Stimulation®) est principalement indiquée pour :",opts:["Les patients présentant un déficit léger à modéré en phase de rééducation active","Les personnes avec handicaps multiples, lésions cérébrales sévères et capacités perceptives fortement réduites","Les enfants avec TDAH et troubles de l'intégration sensorielle en milieu scolaire"],ans:1,fb:"La stimulation basale s'adresse aux personnes avec besoins importants de soutien, capacités perceptives et communicatives réduites. Elle favorise perception corporelle, communication et développement global."},
 
{ch:"outils",q:"Le TENS en neuroréhabilitation à haute fréquence (20-100 Hz) produit un effet :",opts:["Inhibiteur, réduisant la spasticité par activation des afférences Ib","Facilitateur de l'activation motrice, augmentant l'excitabilité spinale et corticale","Antalgique par gate control uniquement, sans effet sur le mouvement"],ans:1,fb:"TENS haute fréquence (20-100 Hz) : effet facilitateur moteur. Basse fréquence (1-10 Hz) : effet inhibiteur, réduction de la spasticité. Les deux peuvent favoriser la plasticité synaptique en complément de la pratique fonctionnelle."},
 
{ch:"outils",q:"Le MyoPro® se distingue du Myomo e100 car :",opts:["Le Myomo e100 contrôle épaule, coude, poignet et main ; le MyoPro est mono-articulaire au coude","Le MyoPro permet le contrôle volontaire de l'épaule, du coude, du poignet et de la main par amplification du signal EMG résiduel","Le MyoPro est exclusivement utilisé en rééducation hospitalière ; le Myomo à domicile"],ans:1,fb:"Myomo e100 : mono-articulaire (coude, 1 GDL), signal EMG biceps/triceps. MyoPro : multi-articulaire (épaule, coude, poignet, main) contrôlé par amplification du signal EMG des muscles résiduels."},
 
{ch:"outils",q:"Les effecteurs finaux (end-effectors) dans la robotique des membres inférieurs présentent quel avantage par rapport aux exosquelettes ?",opts:["Ils permettent un contrôle plus précis de chaque articulation individuellement","Ils s'adaptent mieux aux différents patients car le contact se fait uniquement via les pieds, sans risque de désalignement articulaire","Ils sont plus adaptés à la marche en milieu communautaire car ils ne limitent pas les mouvements"],ans:1,fb:"Les effecteurs finaux (pieds sur des supports) s'adaptent mieux aux différentes morphologies, évitent les risques de désalignement des exosquelettes, et permettent au thérapeute d'accéder au membre pendant la marche."},
 
// ══════════════════════════════════════════════════════════════
// PHASE AIGUË ET SUBAIGUË (15 questions)
// ══════════════════════════════════════════════════════════════
{ch:"phase-aigue",q:"La fenêtre thérapeutique de 24 à 48 heures post-AVC est critique car :",opts:["C'est la seule période où la rééducation est efficace avant que la plasticité ne disparaisse","Les interventions précoces favorisent la réorganisation fonctionnelle et réduisent la mortalité, le handicap et l'institutionnalisation","La neuroplasticité est absente avant 48 heures, puis maximale entre J2 et J7"],ans:1,fb:"Les interventions précoces (< 24-48h si stabilité clinique) favorisent la neuroplasticité précoce et réduisent significativement la mortalité, les séquelles et le recours à l'institutionnalisation (Rodgers & Price, 2017)."},
 
{ch:"phase-aigue",q:"Les 'zones de pénombre' après un AVC ischémique sont :",opts:["Des zones de nécrose irréversible constituant le cœur de la lésion","Des zones temporairement affectées par l'ischémie, potentiellement récupérables si la perfusion est rétablie rapidement","Des régions distantes affectées par le diaschisis"],ans:1,fb:"La pénombre ischémique entoure le cœur nécrotique. Ces cellules sont dysfonctionnelles mais vivantes. La reperfusion rapide (thrombolyse) et la rééducation précoce peuvent limiter leur conversion en nécrose."},
 
{ch:"phase-aigue",q:"En phase de choc neural aigu, l'objectif thérapeutique principal du kinésithérapeute est :",opts:["Initier un entraînement intensif actif pour exploiter la neuroplasticité maximale","Offrir l'expérience du mouvement, prévenir les complications (escarres, TVP, rétractions) et collaborer avec l'équipe interdisciplinaire","Évaluer complètement les déficits neurologiques par les échelles validées"],ans:1,fb:"En phase de choc neural : neurotransmission réduite, apprentissage impossible. Priorité = prophylaxie des complications, positionnement thérapeutique, mobilisation passive/active-assistée douce et soutien de l'équipe."},
 
{ch:"phase-aigue",q:"Le choc médullaire après lésion médullaire se caractérise par :",opts:["Spasticité sévère, hyperréflexie et douleurs neuropathiques intenses","Hypotonie, aréflexie et absence de réponses autonomiques sous le niveau lésionnel","Dysréflexie autonome avec hypertension paroxystique et bradycardie"],ans:1,fb:"Le choc médullaire est une perte transitoire de toutes les fonctions sous-lésionnelles (motricité, sensibilité, reflexes, autonomique). Il précède l'installation progressive de la spasticité en phase subaiguë."},
 
{ch:"phase-aigue",q:"Les lésions cervicales hautes (C1-C4) représentent un risque vital en phase aiguë principalement en raison de :",opts:["L'instabilité hémodynamique et du risque d'hypotension orthostatique","Du risque d'insuffisance respiratoire nécessitant une ventilation mécanique","De la dysréflexie autonome et des troubles sphinctériens"],ans:1,fb:"Les lésions C1-C4 atteignent les racines du nerf phrénique (C3-C5), compromettant la fonction diaphragmatique → risque d'insuffisance respiratoire et nécessité de ventilation mécanique."},
 
{ch:"phase-aigue",q:"Pour le positionnement thérapeutique en phase aiguë, les changements de position sont recommandés toutes les :",opts:["30 minutes","2 à 3 heures","6 à 8 heures"],ans:1,fb:"Le positionnement fonctionnel alternant toutes les 2-3 heures est recommandé pour prévenir les escarres, les rétractions et favoriser la stimulation sensorimotrice (Langhorne et al., 2011; Gracies, 2005)."},
 
{ch:"phase-aigue",q:"En phase subaiguë, 'la neurotransmission est réactivée et l'apprentissage est possible'. Cela implique cliniquement :",opts:["De maintenir une approche exclusivement passive pour protéger le SNC","De proposer des activités fonctionnelles actives (transferts, station debout, marche si possible) tout en prévenant la plasticité maladaptative","De réduire la fréquence des séances car le patient peut désormais s'entraîner seul"],ans:1,fb:"Phase subaiguë = fenêtre d'apprentissage active. On introduit les changements actifs de posture, transferts, rééducation à la marche, utilisation de la main dans des tâches fonctionnelles, tout en évitant les compensations stéréotypées."},
 
{ch:"phase-aigue",q:"La dysréflexie autonome est une urgence spécifique aux lésions médullaires :",opts:["En dessous de T6, car le contrôle parasympathique est perdu","Au-dessus de T6, car la perte du contrôle sympathique sous-lésionnel provoque des crises hypertensives potentiellement mortelles","Au niveau lombaire, en raison de l'atteinte des centres de miction sacrés"],ans:1,fb:"La dysréflexie autonome (lésions > T6) : stimulation nociceptive sous-lésionnelle → réponse sympathique massive non inhibée (hypertension sévère, bradycardie, céphalées, sueurs). C'est une urgence médicale."},
 
{ch:"phase-aigue",q:"Concernant l'épaule douloureuse en phase aiguë post-AVC, la poleothérapie sans surveillance est contre-indiquée car :",opts:["Elle provoque une spasticité réflexe immédiate des muscles péri-articulaires","Elle peut provoquer inflammation, douleur accrue et risque de subluxation sans contrôle scapulaire","Elle stimule les voies afférentes douloureuses et aggrave l'œdème cérébral"],ans:1,fb:"La poleothérapie (poulie avec le bras sain tirant le bras affecté) sans surveillance peut créer des forces de distraction sur une épaule hypotone, risquant subluxation, inflammation et syndrome épaule-main."},
 
{ch:"phase-aigue",q:"Les rétractions musculaires en phase aiguë neurologique sont principalement dues à :",opts:["L'hyperactivité des muscles spastiques provoquant un raccourcissement actif permanent","L'immobilité prolongée et l'absence de mise en charge, entraînant une perte de sarcomères en série","L'activation des réflexes archaïques perturbant l'élongation musculaire"],ans:1,fb:"L'immobilité réduit le nombre de sarcomères en série → raccourcissement musculaire → rétraction. La kinésithérapie précoce (mobilisations passives, positionnement en élongation) prévient ce phénomène."},
 
{ch:"phase-aigue",q:"Dans le TCC aigu grave (GCS < 8), la priorité kinésithérapique est :",opts:["Initier immédiatement la rééducation à la marche pour prévenir l'atrophie","Adapter les interventions à la stabilité clinique : physiothérapie respiratoire, gestion posturale, stimulation sensorielle de base","Évaluer les fonctions exécutives et cognitives pour établir le pronostic fonctionnel"],ans:1,fb:"TCC grave : priorité à la stabilité clinique. Kine = physiothérapie respiratoire (pneumonie d'aspiration), gestion posturale (escarres), mobilisations douces (rétractions), stimulation sensorielle de base (tactile, auditive, visuelle)."},
 
{ch:"phase-aigue",q:"La mobilisation très précoce (< 24h) après AVC ischémique est :",opts:["Contre-indiquée dans tous les cas car elle aggrave l'œdème cérébral","Sûre si le patient est hémodynamiquement stable et peut améliorer certains outcomes à court et long terme selon Lou et al. (2024)","Recommandée uniquement pour les AVC hémorragiques, pas les AVC ischémiques"],ans:1,fb:"Une méta-analyse récente (Lou et al., 2024) indique que la mobilisation très précoce (< 48h) est sûre si la stabilité hémodynamique est assurée et peut améliorer certaines mesures. La recommandation NICE NG128 va dans ce sens."},
 
{ch:"phase-aigue",q:"L'entraînement du tronc en phase subaiguë post-AVC améliore selon les preuves :",opts:["Exclusivement l'équilibre statique assis, sans effet sur la marche","Le contrôle du tronc, l'équilibre assis et la mobilité fonctionnelle ; combiné avec des tâches des MS, il améliore aussi la récupération du bras","Principalement la spasticité des membres inférieurs par activation des voies inhibitrices descendantes"],ans:1,fb:"Thijs et al. (Cochrane 2023) : l'entraînement du tronc améliore contrôle du tronc, équilibre assis et mobilité fonctionnelle. Des essais montrent qu'associé aux MS (contrainte du tronc), il améliore aussi la récupération du bras."},
 
{ch:"phase-aigue",q:"La thrombose veineuse profonde (TVP) en phase aiguë neurologique est principalement prévenue par :",opts:["La restriction des mobilisations pour éviter l'embolie pulmonaire","La mobilisation précoce, le positionnement correct et les protocoles médicaux anticoagulants","L'application de froid local sur les membres inférieurs pour réduire la vasodilatation"],ans:1,fb:"La TVP est favorisée par l'immobilité. La prévention repose sur la mobilisation précoce (passif/actif), le positionnement correct des membres inférieurs, et les anticoagulants préventifs prescrits médicalement."},
 
{ch:"phase-aigue",q:"Les ajustements posturaux scapulaires (Oz et al., 2024) en phase aiguë post-AVC améliorent significativement :",opts:["La spasticité du membre supérieur affecté par inhibition réflexe","Le contrôle du tronc chez les patients présentant un AVC aigu","La sensibilité superficielle et profonde du membre supérieur parétique"],ans:1,fb:"Oz, Duray & Cetıslı Korkmaz (2024) : les exercices scapulaires améliorent significativement le contrôle du tronc chez les patients avec AVC aigu, soulignant l'importance du travail proximal précoce."},
 
// ══════════════════════════════════════════════════════════════
// TONUS ET SENSIBILITÉ (15 questions)
// ══════════════════════════════════════════════════════════════
{ch:"tonus",q:"La composante non-neurale du tonus musculaire correspond à :",opts:["L'activité réflexe médiée par les réflexes myotatiques spinaux","Les propriétés viscoélastiques intrinsèques du tissu musculaire et conjonctif","Le contrôle descendant par les voies corticospinales"],ans:1,fb:"Le tonus musculaire a deux composantes : neurale (activité réflexe, voies descendantes) et non-neurale (propriétés viscoélastiques du muscle et tissu conjonctif, protéine titine)."},
 
{ch:"tonus",q:"Le phénomène de 'canif' (clasp-knife) est caractéristique de :",opts:["La rigidité parkinsonienne","La spasticité du syndrome du premier motoneurone","L'hypotonie cérébelleuse"],ans:1,fb:"Le phénomène de canif = résistance initiale à l'étirement rapide qui cède brusquement (comme un canif). C'est un signe clinique de la spasticité, liée à la vitesse d'étirement (Lance, 1980)."},
 
{ch:"tonus",q:"Sur l'échelle d'Ashworth modifiée, un score de 3 correspond à :",opts:["Résistance sur toute l'amplitude, mouvement facile","Augmentation considérable du tonus, mouvements passifs difficiles","Partie affectée rigide en flexion ou extension"],ans:1,fb:"Score Ashworth modifié : 0 = pas d'augmentation ; 1 = légère ; 1+ = blocage sur <1/2 amplitude ; 2 = tonus augmenté mais mouvement facile ; 3 = augmentation considérable, mouvement difficile ; 4 = rigidité."},
 
{ch:"tonus",q:"Dans l'échelle de Tardieu, V3 correspond à :",opts:["Un étirement très lent permettant d'obtenir R2","Un étirement à la vitesse de chute par gravité","Un étirement aussi rapide que possible permettant d'obtenir R1"],ans:2,fb:"Vitesses Tardieu : V1 = très lent (→ R2, amplitude max) ; V2 = vitesse de chute par gravité ; V3 = aussi rapide que possible (→ R1, angle d'accrochage spastique)."},
 
{ch:"tonus",q:"Le tonus postural est défini comme :",opts:["La résistance maximale des muscles à l'étirement forcé","Un niveau faible mais continu de tension musculaire distribuée globalement, nécessaire au maintien de la posture et à la préparation au mouvement","L'activation phasique des muscles antigravitaires lors d'un déséquilibre soudain"],ans:1,fb:"Le tonus postural (Gurfinkel et al., 2006) : activation de faible intensité, répartie globalement, continue, modulée par les afférences sensorielles et le contrôle central. Base de l'alignement et des APA."},
 
{ch:"tonus",q:"La kinesthésie évalue :",opts:["La capacité à identifier des objets uniquement par le toucher sans la vision","La capacité à détecter la direction et la vitesse d'un mouvement passif articulaire","La proprioception statique : reconnaître la position articulaire sans voir le membre"],ans:1,fb:"Kinesthésie = sens du mouvement (direction + vitesse). Sens de la position articulaire (JPS/SPA) = proprioception statique. Stéréognosie = reconnaissance d'objets par le toucher (sensibilité corticale)."},
 
{ch:"tonus",q:"L'EMG de surface est utile pour l'évaluation du tonus car :",opts:["Il mesure directement la tension passive du muscle au repos sans activité","Il enregistre l'activité électrique musculaire et différencie les composantes neurales (réflexes) des composantes non neurales (viscoélasticité)","Il détecte spécifiquement la spasticité indépendamment de la vitesse d'étirement"],ans:1,fb:"L'EMG de surface permet de différencier la composante neurale (réflexes, co-contractions) et non neurale (viscoélasticité) du tonus musculaire, et de monitorer en temps réel les changements pendant les interventions."},
 
{ch:"tonus",q:"Le Nottingham Sensory Assessment (NSA) évalue trois niveaux de sensibilité :",opts:["Tactile légère, douleur et température uniquement","Sensibilité superficielle (toucher, douleur, température), proprioception (position, cinesthésie) et sensibilité corticale (stéréognosie, graphesthésie)","Vibration, pression profonde et discrimination de deux points"],ans:1,fb:"NSA (Wu et al., 2016) : 3 niveaux — superficielle (toucher léger, douleur, température), profonde (position articulaire, kinesthésie) et corticale (stéréognosie, discrimination 2 points, graphesthésie)."},
 
{ch:"tonus",q:"Les monofilaments de Semmes-Weinstein évaluent :",opts:["La sensibilité profonde par stimulation des récepteurs articulaires","La sensibilité cutanée superficielle par application d'une pression standardisée jusqu'à déflexion en C","La discriminination de deux points statique avec un compas de Weber"],ans:1,fb:"Les monofilaments de Semmes-Weinstein : appliqués perpendiculairement jusqu'à déflexion en C, ils délivrent une pression standardisée. La plus petite épaisseur perçue définit le seuil de sensibilité cutanée."},
 
{ch:"tonus",q:"La dynamométrie isocinétique pour évaluer le tonus présente l'avantage de :",opts:["Ne pas nécessiter d'équipement spécialisé, applicable directement en clinique","Fournir des données quantitatives précises du couple résistif à différentes vitesses, avec haute reproductibilité","Évaluer simultanément les composantes neurales et viscoélastiques sans calcul supplémentaire"],ans:1,fb:"La dynamométrie isocinétique utilise des servomoteurs pour mobiliser à vitesse constante et mesurer la résistance (torque). Elle offre précision, comparaison de vitesses et haute reproductibilité. Son coût limite l'usage clinique."},
 
{ch:"tonus",q:"Dans l'évaluation du 'Holding' selon le protocole Bobath, on observe :",opts:["La capacité à maintenir automatiquement la position après placement passif","La capacité à placer volontairement le segment dans une position indiquée et à le maintenir 5-10 secondes","La réponse musculaire à une perturbation soudaine imprévue du segment"],ans:1,fb:"Holding : le thérapeute place le segment controlatéral dans une position et le patient doit placer volontairement le segment affecté dans la même position et le maintenir (contrôle actif volontaire)."},
 
{ch:"tonus",q:"La voie lemniscale-dorsale (colonnes postérieures) transmet :",opts:["La douleur et la température vers le cortex somesthésique controlatéral","La proprioception consciente, les vibrations et le toucher fin discriminatif (épicritique)","Les informations proprioceptives inconscientes vers le cervelet"],ans:1,fb:"Colonnes dorsales → lemnisque médian → thalamus → cortex pariétal : proprioception consciente, vibrations, toucher fin, discrimination spatiale. Spinothalamique : douleur, température. Spinocérébelleux : proprioception inconsciente."},
 
{ch:"tonus",q:"La pratique clinique du verre d'eau pour évaluer le tonus postural permet d'observer :",opts:["Uniquement la stratégie de cheville dans différentes conditions de surface","Les oscillations de l'eau comme reflet indirect de la capacité d'adaptation du tonus postural aux différentes exigences posturales","La force musculaire isométrique du membre supérieur en position debout"],ans:1,fb:"Le verre d'eau (exercice pratique) : les oscillations reflètent la qualité des micro-ajustements posturaux. Plus les oscillations sont importantes, plus le contrôle postural est déficient ou la demande élevée."},
 
{ch:"tonus",q:"La discrimination de deux points est plus précise au bout des doigts qu'au dos car :",opts:["Les doigts ont plus de muscles intrinsèques permettant une meilleure proprioception","Les champs réceptifs des mécanorecepteurs sont plus petits au bout des doigts, où une plus grande résolution spatiale est fonctionnellement nécessaire","Le cortex somatosensoriel alloue plus de surface au dos qu'aux doigts"],ans:1,fb:"La taille des champs réceptifs varie selon les exigences fonctionnelles. Doigts : petits champs réceptifs → haute résolution spatiale (stéréognosie, manipulation fine). Dos : grands champs → faible résolution nécessaire."},
 
{ch:"tonus",q:"L'hypotonie centrale (d'origine cérébelleuse) se distingue de l'hypotonie périphérique par :",opts:["La présence de fasciculations et d'amyotrophie dans l'hypotonie centrale","La préservation des réflexes ostéotendineux dans l'hypotonie centrale vs leur abolition dans l'hypotonie périphérique","L'absence de tout signe de faiblesse musculaire dans l'hypotonie centrale"],ans:1,fb:"Hypotonie centrale (cérébelleuse) : réflexes conservés voire pendulaires, pas d'amyotrophie ni de fasciculations. Hypotonie périphérique (NMI) : aréflexie, amyotrophie, fasciculations possibles."},
 
// ══════════════════════════════════════════════════════════════
// NEUROSCIENCES APPLIQUÉES (18 questions)
// ══════════════════════════════════════════════════════════════
{ch:"neurosciences",q:"La théorie de l'Embodied Cognition implique cliniquement que :",opts:["La rééducation cognitive doit être séparée de la rééducation motrice","La thérapie neurologique nécessite des environnements offrant des repères naturels et des tâches fonctionnellement significatives ancrées dans le contexte réel","Les processus cognitifs peuvent être rééduqués indépendamment du corps via des exercices computérisés"],ans:1,fb:"L'Embodied Cognition : cognition et corps sont indissociables. En clinique : tâches significatives en contexte réel, environnement naturel, objets fonctionnels plutôt que matériel abstrait."},
 
{ch:"neurosciences",q:"Le système cortico-réticulospinal pontique joue un rôle clé dans :",opts:["Le contrôle sélectif des mouvements fins distaux des doigts","La génération de la stabilité axiale du tronc et des membres inférieurs et les ajustements posturaux anticipatoires","L'inhibition des réflexes spinaux de haut niveau pour permettre la locomotion"],ans:1,fb:"Le réticulo-spinal pontique (ipsilatéral médian) active les muscles axiaux et extenseurs des membres inférieurs, fournit la base posturale pour les mouvements volontaires et coordonne les APA."},
 
{ch:"neurosciences",q:"Une lésion complète du tractus corticospinal latéral entraînerait :",opts:["Principalement une spasticité sévère en raison de la lésion directe des motoneurones alpha","Une perte du fractionnement et de la dextérité distale (mains, pieds), et non uniquement de la spasticité","Une paralysie totale permanente sans récupération possible"],ans:1,fb:"Le tractus corticospinal latéral contrôle la dextérité motrice fine distale. Sa lésion = perte de sélectivité et fractionnement. La spasticité provient de la levée du contrôle inhibiteur cortical sur les voies extrapyramidales."},
 
{ch:"neurosciences",q:"Le système vestibulospinal médian contrôle :",opts:["Les muscles extenseurs ipsilatéraux des membres inférieurs antigravitaires","Les réflexes vestibulo-oculaires et la stabilité céphalique pour le suivi visuel","Le tonus postural global des membres et du tronc bilatéralement"],ans:1,fb:"Vestibulospinal médian (bilatéral, cervical-thoracique) : réflexes vestibulo-oculaires, stabilité de la tête lors des mouvements du tronc, coordination œil-tête. Le vestibulospinal latéral gère les extenseurs antigravitaires."},
 
{ch:"neurosciences",q:"Le 'pusher syndrome' (syndrome de la poussée) après AVC est lié à :",opts:["Une lésion du cortex moteur primaire altérant directement le tonus des membres ipsilésionnels","Une perturbation de l'intégration sensorielle vestibulaire et pariétale altérant le modèle interne de verticalité posturale","Une hyperactivité cérébelleuse générant une déviation posturale ipsilatérale"],ans:1,fb:"Le pusher syndrome résulte d'une altération du traitement de la verticalité posturale par les zones pariétales et thalamiques. Le patient pousse activement du côté sain car il perçoit le côté lésé comme vertical."},
 
{ch:"neurosciences",q:"Le système proprio-spinal (interneurones intrinsèques) joue un rôle clé dans la récupération après lésion médullaire car :",opts:["Il régénère directement les axones lésés par activation des facteurs de croissance nerveux","Il peut créer des circuits de déviation ('detour circuits') reliant les segments au-dessus et en dessous de la lésion","Il inhibe la spasticité sous-lésionnelle par activation des interneurones Ib"],ans:1,fb:"Le système proprio-spinal (Filli & Schwab, 2015) : interneurones reliant différents niveaux médullaires. Après lésion, peuvent former des circuits alternatifs permettant aux signaux suprasegmentaires d'atteindre les circuits distaux."},
 
{ch:"neurosciences",q:"Le système rubrospinal (cortico-rubrospinal) chez l'humain adulte lésé :",opts:["Reste inactif quelle que soit l'étendue de la lésion corticospinale","Peut augmenter son activité en cas de lésion du tractus corticospinal, expliquant en partie la flexion typique du MS hémiparétique","Compense totalement la lésion corticospinale en restaurant la dextérité fine"],ans:1,fb:"Après lésion corticospinale, le système rubrospinal peut devenir hyperactif (études DTI et TMS). Il favorise la flexion du MS et pourrait expliquer le schéma fléchisseur dominant observé en hémiparésie."},
 
{ch:"neurosciences",q:"L'ARAS (Système Activateur Réticulaire Ascendant) joue un rôle primordial dans :",opts:["La coordination des mouvements fins et la correction d'erreurs motrices","Le niveau de conscience, les cycles veille-sommeil et l'éveil général du SNC","La régulation de la pression intracrânienne après un TCC"],ans:1,fb:"L'ARAS (formation réticulaire → cortex) régule l'éveil, la conscience et les cycles veille-sommeil. Une lésion à ce niveau provoque des états d'altération de la conscience allant jusqu'au coma."},
 
{ch:"neurosciences",q:"La 'corticalisation de la marche' chez un patient neurologique signifie que :",opts:["Le cortex moteur primaire reprend directement le contrôle des GCP spinaux","La marche, normalement automatique, requiert une attention corticale consciente accrue, réduisant les capacités de double tâche","Le cervelet compense la lésion corticale en automatisant de nouveaux schémas de marche"],ans:1,fb:"La marche normalement automatique (générateurs spinaux + sous-corticaux) devient 'corticalisée' après lésion neurologique : le patient doit y penser consciemment, épuisant les ressources attentionnelles disponibles pour d'autres tâches."},
 
{ch:"neurosciences",q:"Les ganglions de la base jouent un rôle dans l'apprentissage moteur grâce à :",opts:["La correction des erreurs motrices en temps réel via les boucles cérébello-corticales","Le système de récompense dopaminergique favorisant l'apprentissage par renforcement positif","La modulation directe des motoneurones alpha spinaux pour ajuster la force musculaire"],ans:1,fb:"Les ganglions de la base interviennent dans l'apprentissage procédural et par renforcement via la voie dopaminergique nigrostriée. La dopamine signale la récompense et consolide les séquences motrices apprises."},
 
{ch:"neurosciences",q:"Après une lésion cérébelleuse, la compensation par fixation visuelle excessive est problématique car :",opts:["Elle fatigue les muscles oculomoteurs et génère des céphalées","Elle masque les capacités des autres systèmes sensoriels et empêche le réentraînement de l'intégration sensorielle","Elle provoque un nystagmus compensatoire perturbant la stabilité du regard"],ans:1,fb:"La dépendance visuelle excessive limite le réentraînement de l'intégration sensorielle vestibulaire et somatosensorielle. La rééducation cérébelleuse inclut des exercices avec perturbation visuelle contrôlée pour favoriser l'intégration multimodale."},
 
{ch:"neurosciences",q:"Le principe d'Henneman (recrutement des unités motrices) indique que lors d'une contraction volontaire croissante :",opts:["Les fibres rapides (type II) sont recrutées en premier, puis les fibres lentes (type I)","Les fibres lentes (type I, toniques) sont recrutées en premier, puis les rapides (type II, phasiques) au fur et à mesure de l'intensité","Toutes les fibres sont recrutées simultanément selon un signal corticospinal global"],ans:1,fb:"Principe de taille d'Henneman : les petites unités motrices (fibres lentes type I) ont le seuil de recrutement le plus bas → recrutées en premier. Les grandes (rapides type II) sont recrutées en dernier, à forte intensité."},
 
{ch:"neurosciences",q:"Les neurones miroirs activés lors de l'observation d'une action sont situés principalement dans :",opts:["Le cervelet et les ganglions de la base","Le cortex prémoteur et le cortex pariétal inférieur","Le cortex préfrontal dorsolatéral et l'hippocampe"],ans:1,fb:"Les neurones miroirs (découverts chez le singe, Rizzolatti) sont localisés dans le cortex prémoteur (F5) et le cortex pariétal inférieur. Chez l'humain : régions équivalentes (zone de Broca, pariétal inférieur)."},
 
{ch:"neurosciences",q:"La plasticité synaptique de type LTP est induite par :",opts:["Une stimulation répétée à basse fréquence (1 Hz) affaiblissant les connexions synaptiques","Des stimulations répétées à haute fréquence provoquant une augmentation durable de l'efficacité synaptique","L'absence prolongée d'activité neuronale favorisant le renforcement compensatoire des synapses"],ans:1,fb:"La LTP est induite par des stimulations répétitives à haute fréquence → augmentation durable de la transmission synaptique. C'est le modèle cellulaire de l'apprentissage et de la mémoire (Hebb)."},
 
{ch:"neurosciences",q:"L'imagerie par résonance magnétique fonctionnelle (IRMf) a montré que :",opts:["La récupération motrice post-AVC implique exclusivement la réorganisation ipsilésionnelle","La réorganisation corticale controlatérale peut compenser certaines fonctions mais est souvent moins efficace pour les fonctions très spécialisées","La récupération fonctionnelle est toujours corrélée avec la taille de l'activation controlatérale"],ans:1,fb:"L'IRMf révèle que les deux hémisphères participent à la récupération. La réorganisation controlatérale peut compenser mais présente des limites pour la spécialisation fonctionnelle (ex. mouvement fin des doigts)."},
 
{ch:"neurosciences",q:"Le développement corticospinal et la myélinisation des voies motrices s'achèvent chez l'humain :",opts:["À la naissance, permettant un contrôle moteur mature dès le premier mois","Progressivement jusqu'à l'adolescence, la myélinisation des voies associatives pouvant continuer jusqu'à 25 ans","À 3 ans, coïncidant avec l'acquisition de la marche et de la parole"],ans:1,fb:"La myélinisation démarre en prénatal mais s'achève progressivement : voies sensorimotrices primaires d'abord, zones associatives et cortex préfrontal en dernier (jusqu'à l'adolescence, voire 25 ans)."},
 
{ch:"neurosciences",q:"Dans la maladie de Parkinson, le tremblement de repos disparaît ou diminue :",opts:["En position allongée et lors de la fatigue musculaire","Lors des mouvements intentionnels volontaires","Exclusivement sous l'effet de médicaments dopaminergiques"],ans:1,fb:"Tremblement de repos parkinsonien : présent au repos, diminue ou disparaît lors des mouvements volontaires intentionnels (contrairement au tremblement d'action/intention cérébelleux qui augmente lors du mouvement)."},
 
// ══════════════════════════════════════════════════════════════
// PRISE EN CHARGE GLOBALE (12 questions)
// ══════════════════════════════════════════════════════════════
{ch:"global",q:"La dysphagie neurologique compromet la sécurité (aspiration) et l'efficacité (ingestion) de la déglutition. Les 3 risques majeurs sont :",opts:["Reflux gastro-œsophagien, hypertension et hypoglycémie","Pneumonie par aspiration, déshydratation et malnutrition","Étouffements visibles, perte de poids et déshydratation uniquement"],ans:1,fb:"Dysphagie neurologique : 3 risques majeurs = pneumonie par aspiration (potentiellement mortelle), déshydratation et malnutrition. L'aspiration silencieuse est particulièrement dangereuse car sans signe visible."},
 
{ch:"global",q:"La phase pharyngée de la déglutition implique les paires crâniennes :",opts:["V (trijumeau) et VII (facial)","IX (glossopharyngien) et X (nerf vague), et le tronc cérébral","XI (accessoire) et XII (hypoglosse)"],ans:1,fb:"Phase pharyngée : IX (sensibilité pharyngée, réflexe de déglutition), X (motricité pharyngée et laryngée, fermeture laryngée). Phase orale : V, VII, XII. Phase œsophagienne : X et SNA."},
 
{ch:"global",q:"La posture cyphotique aggrave la dysphagie neurologique car :",opts:["Elle augmente la pression intracrânienne perturbant le contrôle central de la déglutition","L'effondrement du tronc crée un désalignement pharyngo-oesophagien, rompt la synchronisation respiration/déglutition et réduit la protection des voies aériennes","Elle provoque une hyperactivité des muscles élévateurs du larynx compromettant la fermeture laryngée"],ans:1,fb:"La posture cyphotique : désalignement pharynx/œsophage, résistance mécanique accrue, perte de synchronisation respiration-déglutition, fermeture laryngée compromise → risque accru d'aspiration."},
 
{ch:"global",q:"Le CORE a 3 fonctions principales. Laquelle n'en fait PAS partie ?",opts:["Produire et transmettre des forces du centre vers les extrémités","Stabiliser le complexe lombo-pelvien","Contrôler directement la fréquence cardiaque via la pression intraabdominale"],ans:2,fb:"Les 3 fonctions du CORE : 1) Produire/transmettre les forces centre→extrémités, 2) Stabiliser le complexe lombo-pelvien, 3) Réguler la PIA. Le contrôle cardiaque n'est pas une fonction directe du CORE."},
 
{ch:"global",q:"La pression intra-abdominale (PIA) est régulée par :",opts:["Exclusivement le diaphragme thoracique lors de l'inspiration","Le diaphragme thoracique, le plancher pelvien, les muscles abdominaux et les muscles lombaires en synergie","Le sphincter anal externe et les muscles ischio-coccygiens uniquement"],ans:1,fb:"La PIA résulte de l'interaction du diaphragme thoracique (toit), plancher pelvien (plancher), abdominaux (paroi antérieure) et lombaires/paravertébraux (paroi postérieure). Ces 4 éléments = CORE."},
 
{ch:"global",q:"Le centre organisateur de la miction situé dans la formation réticulaire :",opts:["Active directement le muscle detrusor sans implication du cortex","Coordonne la miction et est influencé par l'activation du plancher pelvien qui inhibe la contraction du détrusor","Fonctionne de manière totalement autonome, indépendamment du contrôle volontaire cortical"],ans:1,fb:"Centre de la miction (formation réticulaire pontique) : coordonne la miction via le SNA. L'activation du plancher pelvien inhibe le détrusor (Mahoney, 1977). Le cortex peut exercer un contrôle volontaire supérieur."},
 
{ch:"global",q:"La vessie neurogène est définie comme :",opts:["Une incontinence urinaire due à une faiblesse des muscles du plancher pelvien","Une perte de la fonction normale de la vessie due à une lésion partielle ou totale du système nerveux","Un dysfonctionnement vésical exclusivement d'origine périphérique"],ans:1,fb:"La vessie neurogène = dysfonctionnement vésical causé par une lésion du SN (centrale ou périphérique). C'est l'un des troubles affectant le plus la qualité de vie avec les dysfonctionnements sexuels."},
 
{ch:"global",q:"L'activation du diaphragme thoracique est corrélée à l'équilibre selon :",opts:["Sapsford (2004) qui a montré que la respiration diaphragmatique améliore la PIA","Lee et al. (2019) qui ont montré une corrélation entre épaisseur du diaphragme et capacité d'équilibre statique et dynamique chez des patients post-AVC","Jones et al. (2016) qui ont établi le lien entre formation réticulaire et contrôle respiratoire"],ans:1,fb:"Lee et al. (2019) : des relations significatives entre l'épaisseur du diaphragme, la fonction respiratoire et la capacité d'équilibre chez les patients post-AVC ont été documentées."},
 
{ch:"global",q:"Parmi les AVQ basiques, laquelle exige le plus de planification cognitive et d'organisation spatiale ?",opts:["Dormir et se reposer","S'habiller (séquençage, praxis, organisation)","Se nourrir avec aide partielle"],ans:1,fb:"S'habiller requiert planification séquentielle (quel vêtement d'abord), praxis (boutonner, fermer la fermeture éclair), organisation spatiale (haut/bas, devant/derrière) et motricité fine. C'est une AVQ complexe."},
 
{ch:"global",q:"La Communication Augmentative et Alternative (CAA) est définie comme :",opts:["La rééducation exclusive de l'aphasie chez les patients post-AVC","Tout moyen utilisé par une personne ayant des difficultés à communiquer oralement pour s'exprimer et interagir efficacement","Un système informatique de synthèse vocale réservé aux patients avec SLA"],ans:1,fb:"La CAA (CEAPAT) englobe tous les moyens (gestes, signes, pictogrammes, appareils) permettant à une personne avec difficultés orales de communiquer, qu'ils complètent (augmentatif) ou remplacent (alternatif) la parole."},
 
{ch:"global",q:"La prévention des escarres en phase neurologique aiguë repose sur :",opts:["L'utilisation exclusive de matelas dynamiques alternants sans changement de position","Le changement de position toutes les 2-3 heures, le soin de la peau et les dispositifs orthopédiques protecteurs","L'électrostimulation des zones de pression pour maintenir la vascularisation cutanée"],ans:1,fb:"Prévention escarre = triangle : positionnement actif (changement 2-3h), soin de la peau (peau propre, sèche, hydratée) et dispositifs de redistribution de pression (coussins, matelas statiques/dynamiques)."},
 
{ch:"global",q:"L'échelle de Lawton & Brody a un score maximum de :",opts:["10 points, signifiant une totale indépendance dans les AIVQ","8 points, signifiant une fonctionnalité maximale dans les activités instrumentales","20 points, correspondant à 20 items des activités instrumentales et avancées"],ans:1,fb:"La Lawton & Brody évalue 8 domaines instrumentaux. Score maximum = 8 (fonctionnalité maximale) ; score minimum = 0. Elle est particulièrement utilisée chez les personnes âgées et les patients cognitifs."},
 
// ══════════════════════════════════════════════════════════════
// CIF, ANAMNÈSE ET COGNITIF (18 questions)
// ══════════════════════════════════════════════════════════════
{ch:"cif",q:"La CIF (Classification Internationale du Fonctionnement) a été développée par :",opts:["L'Association Américaine de Physiothérapie (APTA) en 2014","L'OMS en 2001, comme cadre conceptuel biopsychosocial pour codifier le fonctionnement, le handicap et la santé","La Société Espagnole de Rééducation (SERMEF) en collaboration avec le Ministère de la Santé espagnol"],ans:1,fb:"La CIF-OMS (2001) : classification biopsychosociale remplaçant l'ancienne CIDIH. Elle inclut fonctions corporelles, activités, participation et facteurs contextuels (environnementaux et personnels)."},
 
{ch:"cif",q:"Dans le modèle CIF, une 'limitation d'activité' correspond à :",opts:["Des difficultés dans la participation sociale et les rôles professionnels","Des difficultés dans la réalisation de tâches ou d'actions (ex. : besoin d'aide pour se lever du lit)","Une anomalie d'une structure ou fonction corporelle (ex. : spasticité)"],ans:1,fb:"CIF : déficience = structure/fonction corporelle ; limitation = activité (réalisation de tâches) ; restriction = participation (rôles sociaux, familiaux). Les facteurs contextuels modulent les 3 niveaux."},
 
{ch:"cif",q:"Les objectifs SMART doivent être :",opts:["Standardisés, Médicaux, Adaptés, Rééducatifs, Temporels","Spécifiques, Mesurables, Réalisables (Atteignable), Pertinents (Relevant), Limités dans le Temps","Sûrs, Motivants, Applicables, Rapides, Testables"],ans:1,fb:"SMART = Spécifique (quoi exactement), Mesurable (comment savoir), Réalisable (possible), Pertinent (en lien avec les besoins du patient), Temporel (dans quel délai). Ex. : 'Marcher 50m sans aide dans 4 semaines.'"},
 
{ch:"cif",q:"Le modèle biopsychosocial est particulièrement adapté en rééducation car :",opts:["Il se concentre sur la guérison de la maladie, ce qui est l'objectif principal de la rééducation","Il analyse l'impact de la pathologie sur le fonctionnement et la participation en intégrant dimensions biologiques, psychologiques et sociales","Il exclut les facteurs médicaux pour se concentrer sur les déterminants sociaux de la santé"],ans:1,fb:"En rééducation, l'objectif n'est pas de guérir mais d'intervenir sur les séquelles. Le modèle biopsychosocial (CIF) permet de planifier selon l'impact fonctionnel réel et les besoins de participation du patient."},
 
{ch:"cif",q:"L'apraxie idéomotrice se caractérise par :",opts:["Une incapacité à utiliser des outils complexes due à un manque de planification séquentielle","Une incapacité à réaliser des gestes sur commande verbale ou par imitation, sans déficit moteur ni sensoriel primaire","Une difficulté à prononcer les mots due à un trouble de la programmation articulatoire"],ans:1,fb:"Apraxie idéomotrice : incapacité à réaliser des gestes symboliques ou significatifs sur demande (ex. 'montrez comment vous utilisez un peigne') sans déficit moteur ou sensoriel primaire. Liée à des lésions pariétales."},
 
{ch:"cif",q:"Dans la prise en charge des troubles de mémoire en neuroréhabilitation, on exploite prioritairement :",opts:["La mémoire de travail, qui est toujours préservée dans les lésions neurologiques","La mémoire procédurale/motrice (implicite), généralement mieux préservée même en cas d'atteinte déclarative","La mémoire épisodique à long terme par des techniques de récupération progressive"],ans:1,fb:"La mémoire procédurale (implicite, automatisme moteur) est généralement mieux préservée que la mémoire déclarative. Ex. : pédalage, montée d'escaliers, transferts peuvent être automatisés même sans souvenir conscient de la séance."},
 
{ch:"cif",q:"La double tâche en neuroréhabilitation est définie comme :",opts:["Deux séances de rééducation consécutives dans la même journée","L'exécution simultanée de deux tâches exigeant toutes deux un traitement attentionnel, dont l'une est cognitive et l'autre motrice","Un exercice de coordination bimanuelle des membres supérieurs"],ans:1,fb:"La double tâche = exécuter simultanément deux tâches qui requièrent des ressources attentionnelles. Elle révèle les limites du partage attentionnel et prépare aux situations de vie réelle (ex. marcher en parlant)."},
 
{ch:"cif",q:"L'héminégligence (négligence spatiale unilatérale) se distingue de l'hémianopsie par :",opts:["L'héminégligence concerne le champ visuel droit ; l'hémianopsie le champ gauche","L'héminégligence est un déficit attentionnel (ignorer une moitié de l'espace même avec vision intacte) ; l'hémianopsie est un déficit visuel de champ","L'hémianopsie est toujours associée à une lésion droite ; l'héminégligence à une lésion gauche"],ans:1,fb:"Hémianopsie = déficit du champ visuel (voie optique lésée). Héminégligence = déficit attentionnel : le patient perçoit les stimuli mais ne les traite pas. Peut coexister avec une hémianopsie ou apparaître seule."},
 
{ch:"cif",q:"Lors du raisonnement clinique pour établir un diagnostic physiothérapeutique, l'hypothèse d'intervention doit être :",opts:["Fixée uniquement d'après le diagnostic médical, sans évaluation fonctionnelle propre","Établie en reliant les obstacles structuraux et fonctionnels identifiés aux limitations d'activité du patient, puis testée lors de la séance","Identique pour tous les patients ayant le même diagnostic médical"],ans:1,fb:"Le raisonnement clinique : observation → identification des obstacles (primaires/secondaires) → hypothèse (pourquoi cette activité est-elle difficile ?) → test thérapeutique → réexamen de l'hypothèse. C'est un processus itératif."},
 
{ch:"cif",q:"La Goal Attainment Scaling (GAS) est un outil permettant de :",opts:["Mesurer la spasticité selon 5 niveaux d'atteinte fonctionnelle","Définir des objectifs individualisés avec 5 niveaux de performance et d'évaluer leur atteinte en fin d'intervention","Évaluer la qualité de vie du patient selon 5 domaines biopsychosociaux"],ans:1,fb:"GAS : 5 niveaux (-2 : bien en dessous des attentes → +2 : bien au-delà). Elle permet de personnaliser les objectifs, de les quantifier et d'évaluer l'atteinte de façon standardisée, quel que soit le domaine."},
 
{ch:"cif",q:"L'anosognosie post-AVC désigne :",opts:["La perte de la capacité à nommer les objets (manque du mot)","L'incapacité du patient à reconnaître ou admettre ses propres déficits neurologiques","La difficulté à reconnaître les visages familiers après lésion occipito-temporale"],ans:1,fb:"L'anosognosie = manque de conscience de son propre handicap. Le patient nie ou minimise ses déficits (ex. hémiplégie). Fréquente après lésions de l'hémisphère droit. Complique fortement la rééducation."},
 
{ch:"cif",q:"Dans la prise en charge des patients avec confusion ou délires, il est recommandé de :",opts:["Confronter directement les délires pour réorienter le patient vers la réalité","Valider l'émotion sans confronter le délire, renforcer l'orientation avec des repères sensoriels et maintenir un environnement stable et prévisible","Augmenter la stimulation sensorielle pour réduire la confusion par saturation"],ans:1,fb:"Face aux délires/confusions : valider l'émotion ('je comprends que cela vous effraie'), NE PAS confronter directement, proposer une activité sûre et simple, renforcer l'orientation (horloge, calendrier, photos de famille)."},
 
{ch:"cif",q:"Les stéréotypies motrices sont à traiter en priorité uniquement si :",opts:["Elles sont présentes à chaque séance de rééducation","Elles sont préjudiciables ou génèrent un inconfort significatif pour la personne ou son entourage","Le patient présente également un TSA (Trouble du Spectre Autistique)"],ans:1,fb:"Les stéréotypies remplissent des fonctions positives (auto-régulation). L'intervention n'est justifiée que si elles nuisent (blessures, gêne significative, obstacle fonctionnel majeur). L'approche est la redirection positive, pas la suppression."},
 
{ch:"cif",q:"Un déficit du contrôle inhibiteur en neurologie se manifeste notamment par :",opts:["Une difficulté à initier les mouvements volontaires (bradykinésie)","Des réponses impulsives, des mouvements involontaires et des difficultés à arrêter une action en cours","Une incapacité à réaliser des mouvements alternatifs rapides (dysdiadococinésie)"],ans:1,fb:"Déficit inhibiteur (syndrome frontal, TCC) : impulsivité, difficulté à freiner les réponses automatiques, persévération, mouvements non contrôlés. La rééducation utilise des tâches avec signaux GO/NO-GO."},
 
{ch:"cif",q:"L'approche transdisciplinaire en neuroréhabilitation se distingue de l'approche multidisciplinaire car :",opts:["Elle implique davantage de professionnels de santé dans la prise en charge","Les professionnels partagent des objectifs communs et transcendent leurs frontières disciplinaires traditionnelles pour collaborer de façon intégrée","Elle est réservée aux cas neurologiques complexes en unités de soins intensifs"],ans:1,fb:"Multidisciplinaire : chaque professionnel travaille en parallèle selon sa discipline. Transdisciplinaire : objectifs partagés, réunions d'équipe, frontières disciplinaires transcendées pour une prise en charge réellement intégrée."},
 
// ══════════════════════════════════════════════════════════════
// ORTHÈSES (12 questions)
// ══════════════════════════════════════════════════════════════
{ch:"ortho",q:"La différence fondamentale entre une orthèse et une prothèse est :",opts:["L'orthèse est interne ; la prothèse est externe","L'orthèse améliore/complète une fonction existante ; la prothèse remplace totalement un segment corporel absent","L'orthèse est temporaire ; la prothèse est permanente"],ans:1,fb:"Orthèse = dispositif externe qui améliore, stabilise, corrige ou maintient une fonction (AMELIORE). Prothèse = dispositif externe qui remplace un segment manquant (REMPLACE). Les deux font partie de l'orthopédie."},
 
{ch:"ortho",q:"L'AFO Rancho de Los Amigos est fabriqué en :",opts:["Fibre de carbone pour une dynamique optimale à haute activité","Polypropylène, légère et confortable, mais peut provoquer raideur cheville et compression du nerf SPE","Aluminium avec articulation Klenzack permettant 15° de flexion plantaire"],ans:1,fb:"Rancho de Los Amigos : polypropylène (léger, confortable, esthétique). Limite : raideur cheville et tendon d'Achille possible, velcro pouvant comprimer le nerf SPE. S'arrête aux MTP (risque griffes d'orteils)."},
 
{ch:"ortho",q:"Le DAFO (Dynamic Ankle Foot Orthosis) se distingue des AFO conventionnels car :",opts:["Il bloque totalement la flexion plantaire grâce à une rigidité maximale","Il enveloppe presque entièrement le pied en thermoplastique fin et flexible, utilisant les propriétés du matériau pour modifier l'alignement","Il intègre un système de stimulation électrique fonctionnelle pour les dorsiflexeurs"],ans:1,fb:"DAFO : thermoplastique fin, souple, enveloppant le pied. Modifie l'alignement dynamiquement selon la pathologie. Le plus utilisé en neurologie pédiatrique. Contrairement aux AFO rigides, il permet un certain mouvement."},
 
{ch:"ortho",q:"L'orthèse Dynamic Walk (anti-équin en fibre de carbone) est indiquée pour :",opts:["Les patients nécessitant une immobilisation nocturne à 90° de la cheville","Les patients à niveau d'activité élevé ayant besoin de marcher et même courir avec correction dynamique de l'ensemble pied-cheville","Les patients avec spasticité sévère nécessitant un contrôle rigide"],ans:1,fb:"Dynamic Walk (fibre de carbone thermoformable) : pour patients actifs, permet marche et course sans sangles, maintient le positionnement dynamique du complexe pied-cheville. Contraindiquée si spasticité sévère."},
 
{ch:"ortho",q:"La FES appliquée pour le pied tombant (drop foot) stimule :",opts:["Le muscle tibial postérieur pour contrôler l'inversion","Le nerf péronier commun pour activer les dorsiflexeurs pendant la phase d'oscillation de la marche","Le muscle soléaire pour compenser la faiblesse des fléchisseurs plantaires"],ans:1,fb:"FES drop foot : cathode sur le NPC (postérieur à la tête du péroné), anode sur le ventre du tibial antérieur. Muscle et nerf doivent être intacts. Active la dorsiflexion en phase oscillante."},
 
{ch:"ortho",q:"Les orthèses DMO (Dynamic Movement Orthoses) utilisent :",opts:["Un thermoplastique rigide permettant l'immobilisation des articulations pathologiques","Un tissu compressif élastomère doux et souple permettant le mouvement actif assisté","Des ressorts métalliques multi-articulaires guidant le mouvement dans les plans de correction"],ans:1,fb:"DMO : tissu élastomère compressif. Avantages vs attelles statiques : permettent mouvement actif, favorisent neuroplasticité par rétroaction sensorielle, s'adaptent à la pratique fonctionnelle, meilleure tolérance."},
 
{ch:"ortho",q:"L'orthèse Stanmore Flail Arm est indiquée pour :",opts:["Les paralysies partielles du plexus brachial avec main fonctionnelle préservée","Les paralysies complètes du plexus brachial : supporte le poids du bras, prévient la luxation gléno-humérale et peut restaurer la préhension","Les séquelles d'AVC avec hémiplégie flasque du membre supérieur"],ans:1,fb:"L'orthèse Stanmore Flail Arm (paralysie complète plexus brachial) : soutient le poids du bras, prévient la luxation gléno-humérale, permet flexion/extension du coude et maintient le poignet en position fonctionnelle."},
 
{ch:"ortho",q:"Le RECIPROCADOR est une orthèse indiquée pour :",opts:["Les adultes paraplégiques souhaitant reprendre la marche communautaire","Les enfants paraplégiques : orthèse bilatérale avec mécanisme réciproque permettant des pas alternés en réduisant la dépense énergétique","Les patients avec lésion médullaire incomplète en phase de récupération active"],ans:1,fb:"Reciprocador : enfants paraplégiques. Ceinture glutéo-sacrée + contention thoracique + mécanisme réciproque (extension d'une hanche → flexion de l'autre via câble arqué). Permet marche à 4 temps, moins fatigante."},
 
{ch:"ortho",q:"Les effets indésirables potentiels des orthèses incluent :",opts:["Uniquement les érosions cutanées aux points de pression","Érosions cutanées, faiblesse/atrophie musculaire, contractures, restrictions respiratoires et dépendance psychologique","Seulement les contractures musculaires en cas de port prolongé"],ans:1,fb:"Les effets indésirables des orthèses : érosions cutanées, atrophie musculaire (muscles protégés non sollicités), contractures, restrictions respiratoires (corsets), dépendance psychologique, rejet esthétique."},
 
{ch:"ortho",q:"L'impression 3D (fabrication additive) en orthésiologie présente l'avantage de :",opts:["Produire des orthèses plus résistantes que le polypropylène conventionnel pour tout usage","Permettre la conversion de conceptions CAO en prototypes physiques personnalisés avec une adaptation morphologique précise","Réduire le coût à zéro des orthèses sur mesure en milieu hospitalier"],ans:1,fb:"L'impression 3D (CAO → fabrication additive) permet des orthèses parfaitement adaptées à la morphologie individuelle, avec designs complexes impossibles par moulage traditionnel. Elle révolutionne la personnalisation."},
 
{ch:"ortho",q:"Un bipédestateur est indiqué chez l'enfant atteint de paralysie cérébrale car :",opts:["Il remplace la marche fonctionnelle et permet une indépendance locomotrice précoce","Il favorise la minéralisation osseuse (au moins 60 min/jour), améliore la croissance acétabulaire et maintient l'extensibilité musculaire","Il prévient la spasticité par stimulation des récepteurs cutanés plantaires en charge"],ans:1,fb:"Bipédestateur (enfant PC) : minéralisation osseuse (60 min/j, Stuberg 1992), croissance acétabulaire, étirement des muscles fléchisseurs de hanche, stimulation sensorielle en charge. Bénéfices indépendants de la marche."},
 
{ch:"ortho",q:"L'orthèse Neurolux II pour l'épaule est indiquée en cas de :",opts:["Spasticité sévère des muscles rotateurs internes après AVC","Paralysie partielle avec subluxation de l'épaule et/ou syndrome épaule-main, pour repositionner dynamiquement la tête humérale","Luxation traumatique récente de l'épaule dans le contexte d'un TCC"],ans:1,fb:"Neurolux II : paralysie partielle (AVC ou plexus brachial) avec subluxation et/ou syndrome épaule-main. Réduit le poids du bras, repositionne la tête humérale avec sangles réglables en rotation externe."},
 
// ══════════════════════════════════════════════════════════════
// DÉVELOPPEMENT NEUROLOGIQUE (12 questions)
// ══════════════════════════════════════════════════════════════
{ch:"dev",q:"La loi de développement moteur céphalocaudale et proximodistale signifie que le contrôle moteur se développe :",opts:["Des pieds vers la tête et des extrémités vers le centre","De la tête vers le bassin et du centre du corps vers les extrémités","Simultanément dans toutes les directions sans séquence prévisible"],ans:1,fb:"Gesell (1946) : développement céphalocaudal (tête → bassin) et proximodistal (centre → extrémités). Ex. : contrôle céphalique avant contrôle du tronc, puis des membres, puis des mains."},
 
{ch:"dev",q:"L'âge corrigé d'un prématuré né à 30 semaines de gestation, âgé de 4 mois chronologiques, est d'environ :",opts:["4 mois (on n'utilise pas l'âge corrigé après 2 mois)","1,5 à 2 mois corrigés (4 mois - 2,5 mois de prématurité)","3 mois corrigés"],ans:1,fb:"Terme = 40 semaines. Naissance à 30 semaines = 10 semaines de prématurité = 2,5 mois. Âge corrigé = 4 mois - 2,5 mois ≈ 1,5 mois corrigé. On utilise l'âge corrigé jusqu'à 2 ans."},
 
{ch:"dev",q:"Le réflexe de Moro chez le nouveau-né consiste en :",opts:["Flexion des membres inférieurs à 90° en réponse à une stimulation plantaire","Abduction des membres supérieurs à 90° puis rapprochement vers la ligne médiane en réponse à une chute soudaine de la tête","Extension croisée d'un membre inférieur lorsqu'on fléchit et stimule l'autre"],ans:1,fb:"Réflexe de Moro : chute légère de la tête → abduction/extension bras (phase d'ouverture) → rapprochement vers la ligne médiane (phase d'étreinte). Disparaît vers 4-6 semaines (intensité max) à 3-4 mois (complet)."},
 
{ch:"dev",q:"À 3 mois, le nouveau-né en décubitus ventral devrait présenter :",opts:["Un appui symétrique sur les mains, la tête à 90° et un bassin plat","Un appui symétrique sur les coudes (épitrochléas), la tête à 90° avec rotation libre, dissociation ceinture scapulaire/tête","Un schéma de nageur/natation avec membres en extension totale et élévation du thorax"],ans:1,fb:"3 mois DV : appui symétrique sur les coudes (épitrochléas), tête à 90° avec rotation libre, dissociation CS/tête débutante, appui zone pubienne, diminution flexion des hanches/genoux."},
 
{ch:"dev",q:"La 'préhension volontaire latérale' apparaît chez le nourrisson à environ :",opts:["2 mois, avec saisie en pince radio-digitale","4,5 mois, lors du déplacement du centre de gravité latéralement en décubitus ventral","6 mois, lors de l'acquisition de la position assise autonome"],ans:1,fb:"À 4,5 mois : appui asymétrique sur un coude, triangle à base latérale → centre de gravité se déplace latéralement → possibilité de tendre le bras opposé sans franchir la ligne médiane → préhension latérale volontaire."},
 
{ch:"dev",q:"Le réflexe de préhension palmaire disparaît normalement à :",opts:["3 semaines","3 mois","6 mois"],ans:1,fb:"Le réflexe de préhension palmaire (serrer la main quand on appuie sur la paume) disparaît vers 3 mois. Sa persistance au-delà est un signe neurologique pathologique."},
 
{ch:"dev",q:"Les réactions posturales selon Vojta se caractérisent par :",opts:["Des réponses motrices volontaires apprises par conditionnement","Des réponses motrices du SNC à un changement postural soudain, défini, reproductible et indépendant de la motivation","Des réflexes spinaux segmentaires évalués par percussion tendineuse"],ans:1,fb:"Réactions posturales (Vojta) : réponses à un changement postural soudain, toujours identiques, reproductibles, indépendantes de la motivation. 7 réactions évaluant la maturation du SNC de 0 à 12 mois."},
 
{ch:"dev",q:"La marche automatique (marche néonatale) disparaît normalement vers :",opts:["1 semaine après la naissance","4 semaines après la naissance","3 mois après la naissance"],ans:1,fb:"La marche néonatale (mouvements alternés de marche quand le bébé est tenu debout sur une surface) disparaît vers 4 semaines. C'est un réflexe archaïque médié par les structures sous-corticales."},
 
{ch:"dev",q:"Le 'rocking' chez le nourrisson de 7 mois correspond à :",opts:["Un balancement du tronc en position assise indiquant un trouble de l'équilibre","La mise à quatre pattes avec balancement avant-arrière sans déplacement, précédant la marche à quatre pattes","Un réflexe vestibulaire physiologique de la mise en place du contrôle postural"],ans:1,fb:"Le rocking (7 mois) = position à 4 pattes + balancement avant/arrière. C'est une étape normale précédant la marche à 4 pattes. Il permet de découvrir la relation poids/équilibre dans cette nouvelle position."},
 
{ch:"dev",q:"La préhension en pince digitale (pouce-index) apparaît normalement vers :",opts:["4 mois","9 mois","12 mois"],ans:1,fb:"Pince en tenaille/digitale (pouce-index) : ~9 mois. Avant : prise palmaire globale (3-4 mois), puis pince en tenaille grossière (~7-8 mois), puis pince fine digitale (9-10 mois)."},
 
{ch:"dev",q:"Selon Gesell (1946), le développement moteur est décrit comme :",opts:["Une séquence linéaire stricte et identique pour tous les enfants","Une hiérarchie en spirale (non linéaire) avec alternance d'avancées et de reculs lors de l'acquisition de nouvelles compétences","Un processus aléatoire entièrement déterminé par les stimulations environnementales"],ans:1,fb:"Gesell : développement en spirale (non linéaire). Les enfants peuvent régresser temporairement à des schémas plus primitifs lors de l'apprentissage de compétences nouvelles plus complexes. C'est une dynamique normale."},
 
{ch:"dev",q:"Le test APGAR évalue le nouveau-né à 1 et 5 minutes sur 5 critères dont l'acronyme est :",opts:["Activité, Poids, Gestes, Alimentation, Réflexes","Apparence (couleur), Pouls, Grimace (réflexe), Activité (tonus), Respiration","Alerte, Position, Grasp (préhension), Acuité visuelle, Réponse auditive"],ans:1,fb:"APGAR : Apparence (couleur cutanée), Pouls (fréquence cardiaque), Grimace (réflexe d'irritabilité), Activité (tonus musculaire), Respiration. Score 0-10 ; ≤ 6 = souffrance néonatale."},
 
]; // end questions
var EXTRA_Q = [];
var EXTRA_Q2 = [];
var ALL_Q = MAIN_Q.concat(EXTRA_Q).concat(EXTRA_Q2);
var ALL_Q = MAIN_Q.concat(EXTRA_Q).concat(EXTRA_Q2);

window.ANAT_BANK = ALL_Q.map(function(item) {
  return {
    ch: item.ch,
    label: 'Proced II - ' + item.ch,
    type: 'direct',
    q: item.q,
    opts: item.opts,
    a: item.ans,
    e: item.e
  };
});
